(() => {
  'use strict';
  const C=GameCommon,$=C.$,KEY='english-adventure-v2';
  const fingerprint=text=>{let h=2166136261;for(let i=0;i<text.length;i++)h=Math.imul(h^text.charCodeAt(i),16777619);return `${text.length}:${h>>>0}`};
  const freshGarden=()=>({version:1,app:'garden',settings:{pack:'nature'},custom:[],water:0,suns:0,growth:0,flowers:[],history:[],active:null});
  const freshNavy=()=>({totalArrows:0,history:[],legacyHistory:[],active:null});
  const validGarden=s=>C.validBase(s,'garden')&&C.int(s.water)&&C.int(s.suns)&&C.int(s.growth,99)&&Array.isArray(s.flowers)&&s.flowers.length<=10000&&s.flowers.every(f=>f&&C.int(f.variety,5)&&Number.isFinite(Date.parse(f.at)))&&C.validRound(s.active)&&(s.active===null||['spell','listen'].includes(s.active.mode));
  const validActive=a=>a===null||(a&&typeof a.id==='string'&&C.validWord(a.word)&&C.int(a.index,10000)&&C.int(a.correct,a.index+1)&&C.int(a.streak,10)&&C.int(a.holes,10000)&&C.int(a.batchCorrect,10)&&['audio','sail'].includes(a.mode)&&['word','meaning'].includes(a.language)&&[10,15,20,105].includes(a.seconds)&&Number.isFinite(a.remaining)&&a.remaining>=0&&a.remaining<=a.seconds*1000&&['ready','correct','wrong','won','sunk'].includes(a.phase)&&typeof a.paused==='boolean');
  const validNavy=n=>n&&C.int(n.totalArrows)&&Array.isArray(n.history)&&n.history.length<=20000&&n.history.every(h=>h&&typeof h.id==='string'&&Number.isFinite(Date.parse(h.at))&&C.int(h.total,10000)&&h.total>0&&C.int(h.correct,h.total))&&Array.isArray(n.legacyHistory)&&n.legacyHistory.length<=20000&&n.legacyHistory.every(h=>h&&typeof h.id==='string'&&Number.isFinite(Date.parse(h.at))&&C.int(h.total,10)&&h.total===10&&C.int(h.correct,10))&&validActive(n.active);
  const validate=s=>s&&s.version===2&&s.app==='adventure'&&validGarden(s.garden)&&validNavy(s.navy)&&s.settings&&['audio','sail'].includes(s.settings.mode)&&['word','meaning'].includes(s.settings.language)&&[10,15,20,105].includes(s.settings.seconds)&&Array.isArray(s.imported)&&s.imported.every(x=>typeof x==='string');
  let state,blocked=false;
  function convertLegacy(n){if(!C.validBase(n,'navy')||!C.int(n.totalArrows))throw Error('旧借箭备份不正确');const out=freshNavy();out.totalArrows=n.totalArrows;out.legacyHistory=C.copy(n.history);if(n.active&&Array.isArray(n.active.words)&&n.active.words.every(C.validWord)&&!['done','victory'].includes(n.active.phase)) {const a=n.active;out.active={id:a.id,word:a.words[Math.min(a.index,9)],index:a.index,correct:a.correct||0,streak:0,holes:0,batchCorrect:0,mode:'audio',language:a.mode==='meaning'?'meaning':'word',seconds:20,remaining:20000,phase:a.phase==='answered'?(a.lastOK?'correct':'wrong'):'ready',paused:true,legacy:true}}return out}
  try{const raw=localStorage.getItem(KEY);if(raw){state=JSON.parse(raw);if(!validate(state))throw Error('invalid')}else{state={version:2,app:'adventure',settings:{mode:'audio',language:'word',seconds:20},garden:freshGarden(),navy:freshNavy(),imported:[]};const g=localStorage.getItem('english-garden-v1'),n=localStorage.getItem('english-navy-v1');if(g){const old=JSON.parse(g);if(!validGarden(old))throw Error('garden');state.garden=old;state.imported.push(fingerprint(g))}if(n){const old=JSON.parse(n);state.navy=convertLegacy(old);state.imported.push(fingerprint(n))}if(!validate(state))throw Error('invalid');localStorage.setItem(KEY,JSON.stringify(state))}}catch(e){blocked=true;state={version:2,app:'adventure',settings:{mode:'audio',language:'word',seconds:20},garden:freshGarden(),navy:freshNavy(),imported:[]};C.toast('旧存档无法读取，原数据已保留。请先导出原始备份，或导入有效备份。')}
  function reloadState(){if(blocked)return;try{const raw=localStorage.getItem(KEY);if(raw){const s=JSON.parse(raw);if(!validate(s))throw Error('invalid');state=s}}catch(e){blocked=true;C.toast('存档无法读取，已停止保存并保留原始数据。')}}
  function update(fn){reloadState();if(blocked){C.toast('原存档已保留，请在家长设置备份或恢复。');return false}const next=C.copy(state);fn(next);if(!validate(next)){C.toast('进度未保存，数据校验未通过。');return false}try{localStorage.setItem(KEY,JSON.stringify(next));state=next;return true}catch(e){C.toast('储存空间不足，进度未保存。');return false}}
  let running=false,lastFrame=0,spawnClock=0,targetClock=0,raf=0,drops=[],pendingEnd=false,view='voyage';
  const active=()=>state.navy.active;
  const ended=a=>!a||['won','sunk'].includes(a.phase);
  function renderInventory(){$('inventory').textContent=`💧 ${state.garden.water}　☀ ${state.garden.suns}　🌸 ${state.garden.flowers.length}`}
  function renderBoat(){const a=active();$('arrow-count').textContent=`收箭 ${a?.correct||0} / 10`;$('timer').textContent=`${Math.ceil((a?.remaining??state.settings.seconds*1000)/1000)} 秒`;$('leak-label').textContent=`连续失误 ${a?.streak||0} / 10`;$('holes').innerHTML=Array.from({length:Math.min(a?.holes||0,10)},()=>'<i class="hole"></i>').join('');$('stuck-arrows').innerHTML=Array.from({length:Math.min(a?.correct||0,10)},()=>'<i></i>').join('');$('hero-boat').style.translate=`0 ${(a?.streak||0)*3}px`;$('hero-boat').style.rotate=`${(a?.streak||0)*.65}deg`;$('sail-word').textContent=a?.mode==='sail'?a.word[0]:'';$('replay').hidden=a?.mode==='sail';renderInventory()}
  function renderRecords(){const rows=[...state.navy.legacyHistory,...state.navy.history].slice(-20).reverse();$('records').innerHTML=rows.length?rows.map(h=>`<div class="record-row"><span>${C.escape(new Date(h.at).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}))}<small>${C.escape(h.mode||'旧版借箭')} · ${h.outcome==='sunk'?'草船沉没':h.outcome==='won'?'借箭归来':'旧版记录'}</small></span><strong>${h.correct}/${h.total} · ${Math.round(h.correct/h.total*100)}%</strong></div>`).join(''):'<p class="note">启航后，成绩会记在这里。</p>'}
  function overlay(title,copy,button){$('overlay-title').textContent=title;$('overlay-copy').textContent=copy;$('start').textContent=button;$('overlay').hidden=false}
  function saveRemaining(paused=true){if(ended(active()))return true;const remaining=active().remaining;return update(s=>{s.navy.active.remaining=remaining;s.navy.active.paused=paused})}
  function pause(show=true){running=false;cancelAnimationFrame(raf);C.stopSpeech();if(!ended(active()))saveRemaining(true);if(show&&!ended(active()))overlay('雾江暂歇，进度已保存','剩余时间已暂停。回来后继续这一题，已经获得的奖励不会重复发放。','继续借箭 →')}
  function clearRain(){drops=[];$('rain').replaceChildren();spawnClock=0;targetClock=0}
  function announce(){const a=active();if(!a||ended(a))return;$('cue').textContent=a.mode==='audio'?(a.language==='meaning'?'听英文，点击中文意思':'听英文，点击对应单词'):(a.language==='meaning'?'看船帆，点击中文意思':'看船帆，点击相同单词');if(a.mode==='audio')C.speak(a.word[0],ok=>{if(!ok&&running){$('cue').textContent=`语音不可用：${a.word[0]}（可切换看帆模式）`}})}
  function resume(){reloadState();const a=active();if(ended(a))return start();if(!update(s=>{s.navy.active.paused=false}))return;$('overlay').hidden=true;running=true;lastFrame=performance.now();clearRain();renderBoat();announce();spawn(true);spawn(false);raf=requestAnimationFrame(tick)}
  function chooseWord(){const pool=C.words(state.garden);return C.copy(pool[Math.floor(Math.random()*pool.length)])}
  function start(){if(!ended(active()))return resume();const opts={mode:$('mode').value,language:$('language').value,seconds:Number($('seconds').value)};if(!update(s=>{s.settings=opts;s.navy.active={id:C.uid(),word:chooseWord(),index:0,correct:0,streak:0,holes:0,batchCorrect:0,...opts,remaining:opts.seconds*1000,phase:'ready',paused:true}}))return;$('hero-boat').classList.remove('sinking');$('feedback').textContent='';resume()}
  function shoot(){C.sound('drop');const arrow=document.createElement('span');arrow.className='flight-arrow';arrow.textContent='➶';$('river').append(arrow);setTimeout(()=>arrow.remove(),750)}
  function answer(value){const a=active();if(!running||!a||a.phase!=='ready')return false;const ok=value===a.word[a.language==='meaning'?1:0];const remaining=a.remaining;if(!update(s=>{const r=s.navy.active;r.remaining=remaining;r.phase=ok?'correct':'wrong';if(ok){r.correct++;r.batchCorrect++;r.streak=0;s.navy.totalArrows++;s.garden.water++}else{r.streak++;r.holes++}})){pause();return false}if(ok){shoot();$('feedback').textContent='收箭 +1 · 水滴 +1，时间到自动换词'}else{C.sound('miss');$('feedback').textContent=`船身漏水！记住：${a.word[0]} = ${a.word[1]}`}renderBoat();if(active().streak===10)finish('sunk');return ok}
  function assessBatch(s){const a=s.navy.active;if((a.index+1)%10===0){if(a.batchCorrect>=9)s.garden.suns++;a.batchCorrect=0}}
  function deadline(){const a=active();if(!a||ended(a)||pendingEnd)return;pendingEnd=true;const unanswered=a.phase==='ready';if(!update(s=>{const r=s.navy.active;if(unanswered){r.phase='wrong';r.streak++;r.holes++}r.remaining=0})){pendingEnd=false;pause();return}if(unanswered){C.sound('miss');$('feedback').textContent=`超时，船身漏水：${a.word[0]} = ${a.word[1]}`}if(active().streak===10){pendingEnd=false;return finish('sunk')}if(active().correct>=10){pendingEnd=false;return finish('won')}if(!update(s=>{assessBatch(s);const r=s.navy.active;r.index++;r.word=chooseWord();r.phase='ready';r.remaining=r.seconds*1000})){pendingEnd=false;pause();return}pendingEnd=false;renderBoat();announce();spawn(true);targetClock=0}
  function finish(outcome){running=false;cancelAnimationFrame(raf);C.stopSpeech();if(!update(s=>{const r=s.navy.active;assessBatch(s);r.phase=outcome;r.paused=true;r.remaining=0;if(!s.navy.history.some(h=>h.id===r.id))s.navy.history.push({id:r.id,at:new Date().toISOString(),correct:r.correct,total:r.index+1,mode:r.mode==='audio'?'听音找词':'看帆找词',outcome})})){pause();return}renderBoat();renderRecords();const a=active();if(outcome==='sunk'){$('hero-boat').classList.add('sinking');C.sound('miss');setTimeout(()=>{if(active()?.phase==='sunk')overlay('草船沉没，下次再出发','连续失误十题。已经获得的水滴仍在花园里，放慢速度再试试。','重新启航 →')},1600)}else{C.sound('win');overlay('“啊，谢谢大都督的赐箭！”',`已收齐十支箭，本次正确率 ${Math.round(a.correct/(a.index+1)*100)}%。每十题考核达到90%，额外送一颗太阳。奖励已送到花园。`,'再次启航 →');C.speak('啊，谢谢大都督的赐箭！',undefined,'zh-CN')}}
  function spawn(target=false){const a=active();if(!a||ended(a)||drops.length>=35)return;const pool=C.distractors(a.word,state.garden,12);const word=target?a.word:pool[Math.floor(Math.random()*pool.length)];const b=document.createElement('button');b.type='button';b.className='rain-word';b.textContent=word[a.language==='meaning'?1:0];b.setAttribute('aria-label',`选择 ${b.textContent}`);b.style.fontSize=`${15+Math.random()*3}px`;$('rain').append(b);const width=$('rain').clientWidth-b.offsetWidth-10;let x=5+Math.random()*Math.max(0,width);for(let k=0;k<8&&drops.some(d=>d.y<52&&Math.abs(d.x-x)<Math.max(d.b.offsetWidth,b.offsetWidth)+8);k++)x=5+Math.random()*Math.max(0,width);if(drops.some(d=>d.y<0&&d.x<x+b.offsetWidth+4&&d.x+d.b.offsetWidth+4>x)){b.remove();return}let speed=30+Math.random()*24;for(const old of drops)if(old.x<x+b.offsetWidth+4&&old.x+old.b.offsetWidth+4>x)speed=Math.min(speed,old.speed);const d={b,x,y:-46,speed,angle:Math.random()*6-3};b.style.transform=`translate(${x}px,-46px) rotate(${d.angle}deg)`;b.onclick=()=>{if(answer(b.textContent))b.classList.add('picked')};drops.push(d)}
  function tick(now){if(!running)return;const elapsed=(now-lastFrame)/1000,dt=Math.min(elapsed,.15);lastFrame=now;active().remaining=Math.max(0,active().remaining-elapsed*1000);$('timer').textContent=`${Math.ceil(active().remaining/1000)} 秒`;spawnClock+=dt;targetClock+=dt;if(spawnClock>.42){spawnClock=0;spawn(false)}if(targetClock>1.8){targetClock=0;spawn(true)}const h=$('rain').clientHeight;drops=drops.filter(d=>{d.y+=d.speed*dt;d.b.style.transform=`translate(${d.x}px,${d.y}px) rotate(${d.angle}deg)`;if(d.y>h+45){d.b.remove();return false}return true});if(active().remaining<=0)deadline();if(running)raf=requestAnimationFrame(tick)}
  function switchView(next){pause(false);view=next;$('voyage-view').hidden=next!=='voyage';$('garden-view').hidden=next!=='garden';$('nav-voyage').setAttribute('aria-selected',String(next==='voyage'));$('nav-garden').setAttribute('aria-selected',String(next==='garden'));if(next==='garden')$('garden-frame').src='garden/?embed=1';else{reloadState();renderBoat();renderRecords();renderLanding()}window.scrollTo(0,0)}
  function renderLanding(){const a=active();if(!a)return;renderBoat();if(a.phase==='won')overlay('十支箭，满载而归','奖励已送进花园，随时可以开始新的旅程。','再次启航 →');else if(a.phase==='sunk')overlay('草船沉没，下次再出发','已经获得的水滴都保留了。可以改用看帆模式或慢练。','重新启航 →');else overlay('继续上次的借箭之旅',`已经收集 ${a.correct} 支箭，剩余 ${Math.ceil(a.remaining/1000)} 秒。`,'继续借箭 →')}
  function fillSettings(){const g=state.garden;$('pack').replaceChildren();[...C.PACKS,{id:'custom',name:'我的课本词汇'}].forEach(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=p.name;o.disabled=p.id==='custom'&&g.custom.length<4;$('pack').append(o)});$('pack').value=g.settings.pack;$('custom').value=g.custom.map(w=>`${w[0]}=${w[1]}`).join('\n')}
  function download(data,name){const url=URL.createObjectURL(new Blob([data],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  async function restore(file){if(!file||file.size>5000000){C.toast('请选择不超过5MB的备份。');return false}try{const text=await file.text(),s=JSON.parse(text);pause(false);if(s.app==='adventure'){if(!validate(s))throw Error('invalid');if(!confirm('恢复全部进度会替换当前存档。请先导出当前备份。是否继续？'))return false;localStorage.setItem(KEY,JSON.stringify(s));state=s;blocked=false}else{if(!['garden','navy'].includes(s.app))throw Error('invalid');if(s.app==='garden'&&!validGarden(s))throw Error('invalid');const navy=s.app==='navy'?convertLegacy(s):null;if(blocked)throw Error('blocked');if(state.imported.includes(fingerprint(text))){C.toast('这份旧版备份已导入，不会重复计算奖励。');return false}if(!confirm(`导入旧版${s.app==='garden'?'花园':'借箭'}存档？将替换对应部分的进度，另一个游戏的进度保留。建议先导出全部备份。`))return false;if(!update(n=>{if(s.app==='garden')n.garden=s;else n.navy=navy;n.imported.push(fingerprint(text))}))return false}fillSettings();renderBoat();renderRecords();renderLanding();if(view==='garden')$('garden-frame').src='garden/?embed=1';C.toast('备份已恢复。');return true}catch(e){C.toast('未导入：备份格式不正确，原进度没有改动。');return false}}
  $('start').onclick=()=>{C.sound('drop');ended(active())?start():resume()};$('pause').onclick=()=>pause();$('replay').onclick=()=>{if(running)announce()};$('nav-voyage').onclick=()=>switchView('voyage');$('nav-garden').onclick=$('to-garden').onclick=()=>switchView('garden');$('settings-open').onclick=()=>{pause();reloadState();fillSettings();$('settings-dialog').showModal()};$('settings-close').onclick=()=>{$('settings-dialog').close()};$('pack').onchange=()=>update(s=>{s.garden.settings.pack=$('pack').value});$('save-words').onclick=()=>{try{const words=C.parseWords($('custom').value);if(update(s=>{s.garden.custom=words;s.garden.settings.pack='custom'})){fillSettings();C.toast('课本词汇已保存，两个游戏共用。')}}catch(e){C.toast(e.message)}};$('export').onclick=()=>{pause(false);reloadState();const raw=blocked?localStorage.getItem(KEY)||JSON.stringify({garden:localStorage.getItem('english-garden-v1'),navy:localStorage.getItem('english-navy-v1')}):JSON.stringify(state,null,2);download(raw,`英语花园-全部进度-${new Date().toISOString().slice(0,10)}.json`)};$('import').onchange=e=>restore(e.target.files[0]);
  for(const id of ['mode','language','seconds']){$(id).value=state.settings[id];$(id).onchange=()=>{if(!ended(active()))C.toast('设置会用于下次启航，当前题目保持原玩法。');else update(s=>{s.settings[id]=id==='seconds'?Number($(id).value):$(id).value});if(ended(active()))renderBoat()}}
  document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});window.addEventListener('pagehide',()=>pause(false));window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==$('garden-frame').contentWindow)return;if(e.data==='garden-updated'){reloadState();renderInventory()}});
  fillSettings();renderBoat();renderRecords();renderLanding();if(location.hash==='#garden')switchView('garden');if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').then(()=>navigator.serviceWorker.ready).then(()=>{$('offline-status').textContent='离线资源已准备 · 发音取决于设备的英语语音资源'}).catch(()=>{$('offline-status').textContent='离线资源未准备，请联网重新打开'});
  window.Adventure={get state(){return state},update,validate,validGarden,validNavy,start,resume,pause,answer,deadline,finish,switchView,restore,spawn,get running(){return running},get drops(){return drops}};
})();
