/* Shared local-only helpers. No analytics, account, cloud storage or third-party scripts. */
(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const PACKS = [...(window.PEP_REFERENCE_PACKS||[]),
    {id:'nature',name:'自然与花园',icon:'🌿',words:[['flower','花','🌸'],['tree','树','🌳'],['water','水','💧'],['sun','太阳','☀️'],['rain','雨','🌧️'],['river','河流','🏞️'],['cloud','云','☁️'],['leaf','叶子','🍃'],['bird','鸟','🐦'],['fish','鱼','🐟'],['grass','草','🌱'],['mountain','山','⛰️']]},
    {id:'life',name:'我的一天',icon:'🍎',words:[['apple','苹果','🍎'],['bread','面包','🍞'],['milk','牛奶','🥛'],['book','书','📖'],['school','学校','🏫'],['teacher','老师','🧑‍🏫'],['friend','朋友','🤝'],['morning','早晨','🌅'],['evening','傍晚','🌇'],['homework','家庭作业','✏️'],['library','图书馆','📚'],['breakfast','早餐','🥣']]},
    {id:'action',name:'动作与活动',icon:'🚲',words:[['read','阅读','📖'],['write','写','✍️'],['swim','游泳','🏊'],['run','跑','🏃'],['jump','跳','🐇'],['sing','唱歌','🎤'],['dance','跳舞','💃'],['cook','做饭','🍳'],['clean','打扫','🧹'],['sleep','睡觉','💤'],['draw','画画','🎨'],['walk','走路','🚶']]}
  ];
  const copy = a => JSON.parse(JSON.stringify(a));
  function shuffle(a) {const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
  function uid(){return crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random().toString(36).slice(2)}`}
  function escape(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function toast(message){const t=$('toast');if(!t)return;t.textContent=message;t.classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('visible'),4200)}
  function int(n,max=1000000){return Number.isInteger(n)&&n>=0&&n<=max}
  function validWord(w){return Array.isArray(w)&&w.length===3&&typeof w[0]==='string'&&/^[a-z]+(?:[ '.-][a-z]+)*\.?$/i.test(w[0])&&w[0].length<=40&&typeof w[1]==='string'&&w[1].trim().length>0&&w[1].length<=40&&typeof w[2]==='string'&&w[2].length<=12}
  function validPlanting(s){return (s.selectedSeed===undefined&&s.seedGrowth===undefined)||(int(s.selectedSeed,5)&&Array.isArray(s.seedGrowth)&&s.seedGrowth.length===6&&s.seedGrowth.every(g=>int(g,99))&&s.seedGrowth[s.selectedSeed]===s.growth)}
  function validBase(s,app){return s&&s.version===1&&s.app===app&&s.settings&&(s.settings.pack==='custom'||PACKS.some(p=>p.id===s.settings.pack))&&Array.isArray(s.custom)&&s.custom.length<=1000&&s.custom.every(validWord)&&new Set(s.custom.map(w=>w[0])).size===s.custom.length&&Array.isArray(s.history)&&s.history.length<=20000&&s.history.every(h=>h&&typeof h.id==='string'&&Number.isFinite(Date.parse(h.at))&&int(h.correct,10)&&int(h.total,10)&&h.total===10&&typeof h.mode==='string'&&h.mode.length<30)}
  function validRound(a){return a===null||(a&&typeof a.id==='string'&&Array.isArray(a.words)&&a.words.length===10&&a.words.every(validWord)&&int(a.index,9)&&int(a.correct,10)&&Array.isArray(a.missed)&&a.missed.length<=10&&a.missed.every(validWord)&&['ready','answered','done'].includes(a.phase)&&typeof a.lastOK==='boolean'&&typeof a.mode==='string'&&a.correct+a.missed.length===a.index+(a.phase==='ready'?0:1)&&(a.phase!=='done'||a.index===9))}
  class Store {
    constructor(app,fresh,validate){this.app=app;this.key=`english-${app}-v1`;this.validate=validate;this.state=fresh();this.blocked=false;try{const raw=localStorage.getItem(this.key);if(raw){const data=JSON.parse(raw);if(!validate(data))throw Error('invalid');this.state=data}}catch(e){this.blocked=true;toast('原有存档暂时无法读取，已保留原数据。请先导出备份或导入有效备份。')}}
    update(mutator){if(this.blocked){toast('暂时不能保存，请先恢复有效备份。');return false}const next=copy(this.state);mutator(next);if(!this.validate(next)){toast('进度未保存，请返回后重试。');return false}try{localStorage.setItem(this.key,JSON.stringify(next));this.state=next;return true}catch(e){toast('当前浏览器无法保存，请检查储存空间和隐私模式。');return false}}
    export(){let data;try{const raw=localStorage.getItem(this.key);data=this.blocked&&raw?raw:JSON.stringify(this.state,null,2)}catch(e){data=JSON.stringify(this.state,null,2)}const blob=new Blob([data],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${this.app}-进度-${new Date().toISOString().slice(0,10)}.json`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('备份已导出，请保存到“文件”。')}
    async import(file){if(!file)return;if(file.size>5000000){toast('备份文件过大。');return}try{const next=JSON.parse(await file.text());if(!this.validate(next))throw Error('invalid');const count=next.history.length;const detail=this.app==='garden'?`已开 ${next.flowers.length} 朵花，成长 ${next.growth}/100`:`累计 ${next.totalArrows} 支箭`;if(!confirm(`恢复这份备份？\n${count} 次完整学习；${detail}。\n将替换当前进度，建议先导出当前备份。`))return;localStorage.setItem(this.key,JSON.stringify(next));this.state=next;this.blocked=false;location.reload()}catch(e){toast('未导入：文件格式不正确或储存不可用，原进度没有改动。')}}
  }
  function words(s){return s.settings.pack==='custom'&&s.custom.length>=4?s.custom:PACKS.find(p=>p.id===s.settings.pack)?.words||PACKS[0].words}
  // Sampling with replacement prevents the last unseen answer being forced by a small deck.
  function deck(s,mode){const pool=mode==='spell'?words(s).filter(w=>/^[a-z]+$/i.test(w[0])&&w[0].length<=12):words(s);if(!pool.length)return [];return Array.from({length:10},()=>copy(pool[Math.floor(Math.random()*pool.length)]))}
  const EXTRA=[['window','窗户'],['door','门'],['chair','椅子'],['desk','书桌'],['pencil','铅笔'],['paper','纸'],['orange','橙子'],['banana','香蕉'],['grape','葡萄'],['potato','土豆'],['tomato','西红柿'],['carrot','胡萝卜'],['horse','马'],['sheep','绵羊'],['tiger','老虎'],['elephant','大象'],['rabbit','兔子'],['cat','猫'],['dog','狗'],['duck','鸭子'],['boat','船'],['train','火车'],['bus','公交车'],['bicycle','自行车'],['airplane','飞机'],['happy','开心的'],['sad','难过的'],['beautiful','美丽的'],['small','小的'],['large','大的'],['cold','冷的'],['hot','热的'],['red','红色'],['blue','蓝色'],['yellow','黄色'],['green','绿色'],['black','黑色'],['white','白色'],['sister','姐姐或妹妹'],['brother','哥哥或弟弟'],['mother','妈妈'],['father','爸爸'],['kitchen','厨房'],['bedroom','卧室'],['garden','花园'],['music','音乐'],['computer','电脑'],['picture','图片'],['weekend','周末'],['holiday','假期'],['minute','分钟'],['second','秒'],['today','今天'],['tomorrow','明天'],['yesterday','昨天'],['snow','雪'],['wind','风'],['star','星星'],['moon','月亮'],['sea','大海'],['nose','鼻子'],['eye','眼睛'],['ear','耳朵'],['mouth','嘴巴'],['hand','手'],['foot','脚'],['head','头'],['hair','头发'],['arm','胳膊'],['leg','腿'],['face','脸'],['body','身体'],['coat','外套'],['shirt','衬衫'],['shoes','鞋子'],['socks','袜子'],['hat','帽子'],['dress','连衣裙'],['skirt','裙子'],['trousers','裤子'],['ball','球'],['football','足球'],['basketball','篮球'],['kite','风筝'],['toy','玩具'],['game','游戏'],['park','公园'],['zoo','动物园'],['hospital','医院'],['cinema','电影院'],['shop','商店'],['market','市场'],['street','街道'],['road','道路'],['bridge','桥'],['city','城市'],['village','村庄'],['farm','农场'],['country','国家'],['world','世界'],['king','国王'],['queen','女王'],['bear','熊'],['lion','狮子'],['monkey','猴子'],['panda','熊猫'],['fox','狐狸'],['wolf','狼'],['bee','蜜蜂'],['butterfly','蝴蝶']].map(w=>[...w,'📖']);
  function distractors(word,s,count=3){const lesson=words(s),names=new Set(lesson.map(w=>w[0]));const all=[...PACKS.flatMap(p=>p.words),...EXTRA,...s.custom];const unique=[...new Map(all.map(w=>[w[0],w])).values()].filter(w=>w[0]!==word[0]&&w[1]!==word[1]);const outside=shuffle(unique.filter(w=>!names.has(w[0])));const chosen=outside.slice(0,Math.min(2,count));const remaining=shuffle(unique.filter(w=>!chosen.some(c=>c[0]===w[0])));return chosen.concat(remaining.slice(0,count-chosen.length))}
  function parseWords(raw){const lines=raw.trim().split(/\r?\n/).filter(x=>x.trim());if(lines.length<4||lines.length>1000)throw Error('请填写 4–1000 个单词，每行一组。');const list=lines.map((line,i)=>{const parts=line.split(/[=|\t]/).map(x=>x.trim());const w=[(parts[0]||'').toLowerCase(),parts[1]||'','📖'];if(parts.length!==2||!validWord(w))throw Error(`第 ${i+1} 行格式不正确，请用 apple=苹果。`);return w});if(new Set(list.map(w=>w[0])).size!==list.length)throw Error('有重复英文，请每个英文只保留一行。');return list}
  function fillPacks(select,s){select.replaceChildren();[...PACKS,{id:'custom',name:s.custom.length>=4?'我的课本词汇':'我的课本词汇（请先填写）',icon:'📖'}].forEach(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=`${p.icon} ${p.name} · ${p.words?.length??s.custom.length}词条`;o.disabled=p.id==='custom'&&s.custom.length<4;select.append(o)});select.value=s.settings.pack==='custom'&&s.custom.length<4?'pep5-all':s.settings.pack}
  function parentSetup(store,onChange){fillPacks($('pack'),store.state);$('pack').onchange=e=>{if(store.update(s=>{s.settings.pack=e.target.value}))onChange?.()};$('custom').value=store.state.custom.map(w=>`${w[0]}=${w[1]}`).join('\n');$('save-words').onclick=()=>{try{const list=parseWords($('custom').value);if(store.update(s=>{s.custom=list;s.settings.pack='custom'})){fillPacks($('pack'),store.state);toast(`已保存 ${list.length} 个课本单词。`);onChange?.()}}catch(e){toast(e.message)}};$('export').onclick=()=>store.export();$('import').onchange=e=>store.import(e.target.files[0]);$('parent-open').onclick=()=>{$('parent-dialog').showModal()};$('parent-close').onclick=()=>{$('parent-dialog').close()}}
  function historyRows(s){if(!s.history.length)return '<p class="muted">还没有完整学习记录，完成一关后就会出现在这里。</p>';return s.history.slice().reverse().slice(0,20).map(h=>`<div class="history-row"><span>${escape(new Date(h.at).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}))}<small>${escape(h.mode)}</small></span><strong>${h.correct}/10 <small>${h.correct*10}%</small></strong></div>`).join('')}
  let speechToken=0,currentUtterance=null;
  function stopSpeech(){window.WordAudio?.stop();speechToken++;try{window.speechSynthesis?.cancel()}catch{};currentUtterance=null}
  function speak(text,done,lang='en-US'){stopSpeech();const token=speechToken;let timer;let ended=false;const finish=ok=>{if(ended||token!==speechToken)return;ended=true;clearTimeout(timer);done?.(ok)};if(lang.startsWith('en')&&window.WordAudio?.has(text)){WordAudio.play(text,finish);return}if(!('speechSynthesis'in window)){finish(false);return}const synth=window.speechSynthesis;const u=new SpeechSynthesisUtterance(text);currentUtterance=u;u.lang=lang;u.rate=.78;const prefix=lang.split('-')[0];const voices=synth.getVoices().filter(v=>v.lang.toLowerCase().startsWith(prefix));u.voice=voices.find(v=>v.localService)||voices[0]||null;u.onend=()=>finish(true);u.onerror=()=>finish(false);timer=setTimeout(()=>finish(false),6500);try{synth.speak(u)}catch{finish(false)}}
  function sound(type){try{const ctx=sound.ctx||(sound.ctx=new(window.AudioContext||window.webkitAudioContext)());ctx.resume();const o=ctx.createOscillator(),g=ctx.createGain();o.connect(g);g.connect(ctx.destination);o.type='sine';o.frequency.value=type==='win'?660:type==='drop'?520:240;g.gain.setValueAtTime(.08,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.25);o.start();o.stop(ctx.currentTime+.26)}catch(e){}}
  function install(){const label=document.createElement('p');label.className='footer';label.id='offline-status';document.querySelector('main').append(label);if('serviceWorker'in navigator&&window.isSecureContext&&location.protocol!=='file:'){label.textContent='首次离线资源准备中…';navigator.serviceWorker.register('../sw.js',{scope:'../'}).then(()=>navigator.serviceWorker.ready).then(()=>{document.documentElement.dataset.offline='ready';label.textContent='离线资源已准备 · 内置词库可离线发音'}).catch(()=>{label.textContent='离线资源尚未准备，请保持联网重新打开。'})}else{label.textContent='通过安全网址打开后，可以准备离线资源。'}}
  class SharedGardenStore extends Store {
    constructor(app,fresh,validate){super(app,fresh,validate);this.shared=app==='garden'&&!!localStorage.getItem('english-adventure-v2');if(this.shared){try{const root=JSON.parse(localStorage.getItem('english-adventure-v2'));if(!validate(root.garden))throw Error('invalid');this.state=root.garden;this.blocked=false}catch(e){this.blocked=true}}}
    update(mutator){if(!this.shared)return super.update(mutator);if(this.blocked)return false;try{const root=JSON.parse(localStorage.getItem('english-adventure-v2'));const next=copy(root.garden);mutator(next);if(!this.validate(next))throw Error('invalid');root.garden=next;if(window.parent!==window&&window.parent.Adventure&&!window.parent.Adventure.validate(root))throw Error('invalid');localStorage.setItem('english-adventure-v2',JSON.stringify(root));this.state=next;window.parent.postMessage('garden-updated',location.origin);return true}catch(e){toast('进度未保存，请检查存档和储存空间。');return false}}
    export(){if(!this.shared)return super.export();const data=localStorage.getItem('english-adventure-v2');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type:'application/json'}));a.download=`英语花园-全部进度-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
    async import(file){if(this.shared&&window.parent.Adventure)return window.parent.Adventure.restore(file);return super.import(file)}
  }
  window.GameCommon={$,$$:(sel)=>document.querySelectorAll(sel),PACKS,copy,shuffle,uid,escape,toast,int,validWord,validBase,validRound,validPlanting,Store:SharedGardenStore,words,deck,distractors,parseWords,parentSetup,historyRows,speak,stopSpeech,sound,install};
})();
