(() => {
 'use strict';
 const C=GameCommon,$=C.$,A=Adventure,D=TrainingData,names={listening:'听力训练',follow:'跟读训练',reaction:'反应训练',meaning:'词义配对',dialogue:'对话练习',translate:'句子翻译'},icons=['🎧','🎙️','⚡','🧩','💬','🌐'];
 let timer=null,deadline=0,media=new Audio(),record=null,stream=null,chunks=[],recordURL=null,playback=new Audio(),recordEpoch=0,audioEpoch=0;
 const state=()=>A.state.training,active=()=>state()?.active;
 const scope=()=>JSON.stringify([A.state.garden.settings.pack,A.state.garden.custom]);
 const save=fn=>A.update(root=>{root.training??={active:null,history:[]};return fn(root.training,root.garden)});
 const sentencePool=()=>{const id=A.state.garden.settings.pack;if(id==='pep5-photo-upper-all')return D.sentences;const unit=/^pep5-photo-upper-u([1-6])$/.exec(id);return unit?D.sentences.filter(s=>s.unit===Number(unit[1])):[]};
 function halt(){audioEpoch++;clearInterval(timer);timer=null;C.stopSpeech();media.pause();playback.pause();if(record?.state==='recording')record.stop();stream?.getTracks().forEach(t=>t.stop());stream=null;recordEpoch++;if(recordURL){URL.revokeObjectURL(recordURL);recordURL=null}}
 function pause(){if(timer&&active()?.phase==='ready'){const left=Math.max(0,Math.min(10000,Math.ceil(deadline-performance.now())));save(t=>{t.active.remaining=left})}halt()}
 function focus(on){document.body.classList.toggle('training-focus',on);window.scrollTo(0,0)}
 function home(){pause();focus(false);$('training-home').hidden=false;$('training-round').hidden=true;$('training-scope').textContent=C.PACKS.find(p=>p.id===A.state.garden.settings.pack)?.name||'我的课本词汇';if(active()&&active().scope!==scope()&&active().phase!=='done')save(t=>{t.active=null});const a=active();$('training-resume').hidden=!a||a.phase==='done';$('training-resume-label').textContent=a?`${names[a.mode]} · 第 ${a.index+1}/10 题`:'';$('training-history').replaceChildren();for(const h of (state()?.history||[]).slice(-10).reverse()){const row=document.createElement('p');row.textContent=`${names[h.mode]} · ${h.mode==='follow'?'完成10次跟读':`答对 ${h.correct}/10`} · ${new Date(h.at).toLocaleDateString('zh-CN')}`;$('training-history').append(row)}}
 function cycle(pool){if(!pool.length)return [];const out=[];while(out.length<10){const batch=C.shuffle(pool);if(out.length&&batch.length>1&&batch[0].en===out.at(-1).en){[batch[0],batch[1]]=[batch[1],batch[0]]}out.push(...batch.slice(0,10-out.length))}return out}
 function start(mode){if(!names[mode])return;halt();const sentence=mode==='dialogue'||mode==='translate'||(mode==='follow'&&$('follow-kind').value==='sentence'),sp=sentencePool();if(sentence&&!sp.length){C.toast('句子资料对应你拍的新版上册，请在家长设置选择“我的课本”上册或单元。');return}
 const wordPool=C.words(A.state.garden).map(w=>({en:w[0],zh:w[1]}));const units=new Set(sp.map(x=>x.unit));const pool=mode==='dialogue'?D.dialogues.filter(d=>units.has(d.unit)):sentence?sp:wordPool;
 const direction=$('translation-direction').value,hear=$('listening-kind').value;
 if(pool.length<10)C.toast(`当前范围有${pool.length}条素材，练完后会循环复习。`);
 const items=cycle(pool).map(w=>{const english=mode==='dialogue'||mode==='translate'&&direction==='zh-en'||(mode==='listening'||mode==='reaction')&&hear==='word';const expected=english?w.en:w.zh;const others=C.shuffle([...new Set(pool.map(p=>english?p.en:p.zh).filter(x=>x!==expected))]).slice(0,3);return {...w,expected,options:C.shuffle([expected,...others]),english,direction,hear}});
 if(!items.length){C.toast('当前范围没有适用的练习。');return}if(!save(t=>{t.active={id:C.uid(),mode,scope:scope(),items,index:0,correct:0,remaining:10000,phase:'ready',submitted:'',ok:false}}))return;render(true)}
 function audio(text,file){const token=++audioEpoch;C.stopSpeech();media.pause();if(file){media.src=file;media.play().catch(()=>{if(token!==audioEpoch)return;$('training-audio-note').textContent='未能播放，请点“听示范”重试。'})}else C.speak(text,ok=>{if(token===audioEpoch&&!ok)$('training-audio-note').textContent='未能播放，请点“听示范”重试。'})}
 function listen(){const a=active();if(!a||a.phase==='done')return;const w=a.items[a.index];WordAudio.unlock();audio(a.mode==='dialogue'?w.q:w.en,a.mode==='dialogue'?w.qAudio:w.audio)}
 function render(autoplay=false){halt();const a=active();if(!a)return home();focus(true);$('training-home').hidden=true;$('training-round').hidden=false;const w=a.items[a.index],answered=a.phase!=='ready';document.querySelector('.training-card').classList.toggle('reviewing',answered);$('training-count').textContent=`${names[a.mode]} · ${a.index+1}/10`;$('training-audio-note').textContent='';$('training-record').textContent='🎙️ 录一段';$('training-choices').replaceChildren();$('training-review').hidden=!answered;$('training-next').hidden=!answered;$('training-next').textContent=a.index===9?'查看收获 →':'下一题 →';$('training-record').hidden=a.mode!=='follow'||answered;$('training-self').hidden=a.mode!=='follow'||answered;$('training-playback').hidden=true;$('training-listen').hidden=a.mode==='meaning';$('training-timer').hidden=a.mode!=='reaction'||answered;
 $('training-prompt').textContent=a.mode==='follow'?w.en:a.mode==='meaning'?w.en:a.mode==='translate'?(w.direction==='zh-en'?w.zh:w.en):a.mode==='dialogue'?`听问句，选合适的回答。${w.context}`:a.mode==='reaction'?'10秒内选对，点亮闪电！':'听英文，选'+(w.hear==='word'?'对应单词':'中文意思');
 $('training-description').textContent=a.mode==='follow'?w.zh: a.mode==='translate'?'选择对应翻译':a.mode==='meaning'?'把这个英文与中文意思配成一对':'';
 if(a.mode!=='follow')for(const option of w.options){const b=document.createElement('button');b.type='button';b.className='training-choice';b.textContent=option;b.disabled=answered;b.onclick=()=>answer(option);if(answered){if(option===w.expected)b.classList.add('correct');if(option===a.submitted&&!a.ok)b.classList.add('incorrect')} $('training-choices').append(b)}
 $('training-review').textContent=answered?(a.mode==='follow'?`已完成跟读：${w.en} = ${w.zh}。这次记为练习完成，不评发音准确率。`:`${a.ok?'✓ 答对':'✗ '+(a.submitted==='__timeout__'?'超时':'答错')} · 正确答案：${w.en} = ${w.zh}${a.mode==='dialogue'?'；问句：'+w.q:''}`):'';
 if(a.phase==='done'){focus(false);$('training-prompt').textContent='本轮训练完成';$('training-description').textContent=a.mode==='follow'?'完成10次跟读，收获10个练习水滴，不计准确率。':`答对 ${a.correct}/10，获得 ${a.correct} 个水滴${a.correct>=9?'和1个太阳':''}。`; $('training-choices').replaceChildren();$('training-review').hidden=true;$('training-next').textContent='回训练首页 →';$('training-listen').hidden=true;return}
 if(!answered&&a.mode==='reaction'){deadline=performance.now()+a.remaining;const tick=()=>{const ms=deadline-performance.now();$('training-timer').textContent=`⚡ ${Math.max(0,Math.ceil(ms/1000))} 秒`;if(ms<=0){clearInterval(timer);timer=null;answer('__timeout__')}};tick();if(active()?.phase==='ready')timer=setInterval(tick,100)}
 if(autoplay&&!answered&&['listening','reaction','dialogue','follow'].includes(a.mode))listen()}
 function answer(value){const a=active();if(!a||a.phase!=='ready')return false;const ok=value===a.items[a.index].expected;halt();if(!save((t,g)=>{const r=t.active;if(r.id!==a.id||r.index!==a.index||r.phase!=='ready')return false;r.phase='answered';r.submitted=value;r.ok=ok;if(ok){r.correct++;g.water++}}))return false;C.sound(ok?'drop':'miss');render();return ok}
 function completeFollow(){const a=active();if(a?.mode!=='follow'||a.phase!=='ready')return;answer(a.items[a.index].expected)}
 function next(){const a=active();if(!a||a.phase==='ready')return;if(a.phase==='done')return home();if(!save((t,g)=>{const r=t.active;if(r.index===9){r.phase='done';if(!t.history.some(h=>h.id===r.id)){t.history.push({id:r.id,mode:r.mode,at:new Date().toISOString(),correct:r.correct,total:10});if(r.mode!=='follow'){if(r.correct>=9)g.suns++;g.history.push({id:r.id,mode:names[r.mode],at:new Date().toISOString(),correct:r.correct,total:10})}}}else{r.index++;r.phase='ready';r.remaining=10000;r.submitted='';r.ok=false}}))return;render(true)}
 async function microphone(){if(record?.state==='recording'){record.stop();$('training-record').textContent='🎙️ 录一段';return}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){$('training-audio-note').textContent='这个浏览器不能录音。听示范后自行跟读，再点“我已跟读”。';return}halt();const epoch=recordEpoch;$('training-record').disabled=true;try{const captured=await navigator.mediaDevices.getUserMedia({audio:true});if(epoch!==recordEpoch||active()?.phase!=='ready'||document.hidden){captured.getTracks().forEach(t=>t.stop());return}stream=captured;chunks=[];record=new MediaRecorder(stream);record.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};record.onstop=()=>{captured.getTracks().forEach(t=>t.stop());if(epoch!==recordEpoch||!chunks.length)return;recordURL=URL.createObjectURL(new Blob(chunks,{type:record.mimeType}));playback.src=recordURL;$('training-playback').hidden=false;$('training-record').textContent='🎙️ 重新录音';$('training-audio-note').textContent='录音只供本题回听，离开后释放。'};record.start();$('training-record').textContent='⏹ 停止录音';$('training-audio-note').textContent='正在录音…';setTimeout(()=>{if(epoch===recordEpoch&&record?.state==='recording')record.stop()},15000)}catch{$('training-audio-note').textContent='没有取得麦克风权限。可以听示范后自行跟读。'}finally{$('training-record').disabled=false}}
 $('training-modes').innerHTML=Object.entries(names).map(([key,name],i)=>`<button class="training-mode" data-training="${key}"><span>${icons[i]}</span><strong>${name}</strong><small>${['听英文选单词或意思','听示范、跟读、录音回听','十秒挑战，练习反应','英文与中文意思配对','课本问答，选合适回复','中译英 / 英译中'][i]}</small></button>`).join('');
 document.querySelectorAll('[data-training]').forEach(b=>b.onclick=()=>start(b.dataset.training));$('training-continue').onclick=()=>{if(active()?.scope!==scope()){home();C.toast('词库已改变，请重新开始训练。')}else render(true)};$('training-restart').onclick=()=>start(active().mode);$('training-exit').onclick=home;$('training-next').onclick=next;$('training-listen').onclick=listen;$('training-record').onclick=microphone;$('training-playback').onclick=()=>playback.play().catch(()=>C.toast('回听未开始，请再点一次。'));$('training-self').onclick=completeFollow;
 document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});window.addEventListener('pagehide',pause);
 window.EnglishTraining={home,start,answer,next,pause,render,completeFollow,sentencePool,get active(){return active()},get media(){return media}};
})();
