(() => {
 'use strict';
 const C=GameCommon,$=C.$,A=Adventure,D=TrainingData,names={listening:'听力训练',follow:'跟读训练',reaction:'反应训练',meaning:'穿越星门',dialogue:'对话练习',translate:'句子翻译'},icons=['🎧','🎙️','⚡','🧩','💬','🌐'];
 let timer=null,deadline=0,media=new Audio(),record=null,stream=null,recordURL=null,playback=new Audio(),recordEpoch=0,audioEpoch=0,pressWanted=false,micPending=false,holdTimer=null,nextUnlockTimer=null,story=new Audio(),battlePlaybackEpoch=0;
 const state=()=>A.state.training,active=()=>state()?.active;
 const scope=()=>JSON.stringify([A.state.garden.settings.pack,A.state.garden.custom]);
 const save=fn=>A.update(root=>{root.training??={active:null,history:[]};return fn(root.training,root.garden,root)});
 const campaignLevel=a=>window.BattleCampaign?.level(a||active());
 const timeLimit=a=>campaignLevel(a)?campaignLevel(a).seconds*1000:10000;
 const sentencePool=()=>{const id=A.state.garden.settings.pack;if(id==='pep5-photo-upper-all')return D.sentences;const unit=/^pep5-photo-upper-u([1-6])$/.exec(id);return unit?D.sentences.filter(s=>s.unit===Number(unit[1])):[]};
 function halt(){window.WordRealm?.pause();battlePlaybackEpoch++;media.onended=null;media.onerror=null;pressWanted=false;clearTimeout(holdTimer);clearTimeout(nextUnlockTimer);nextUnlockTimer=null;$('training-next').disabled=false;document.querySelector('.training-card')?.classList.remove('battle-resolving','battle-intro-active');story.pause();window.BattleAudio?.stop();window.DialogueBattle?.stop();window.TrainingQuest?.stop();audioEpoch++;clearInterval(timer);timer=null;C.stopSpeech();media.pause();playback.pause();if(record?.state==='recording')record.stop();stream?.getTracks().forEach(t=>t.stop());stream=null;recordEpoch++;if(recordURL){URL.revokeObjectURL(recordURL);recordURL=null}}
 function pause(){if(timer&&active()?.phase==='ready'){const left=Math.max(0,Math.min(timeLimit(active()),Math.ceil(deadline-performance.now())));save(t=>{t.active.remaining=left})}halt()}
 function focus(on){document.body.classList.toggle('training-focus',on);window.scrollTo(0,0)}
 function home(){pause();window.BattleCampaign?.apply(null);document.body.classList.remove('training-dialogue','training-realm');window.WordRealm?.stop();focus(false);$('training-home').hidden=false;$('training-round').hidden=true;$('training-scope').textContent=C.PACKS.find(p=>p.id===A.state.garden.settings.pack)?.name||'我的课本词汇';if(active()&&!active().campaign&&active().scope!==scope()&&active().phase!=='done')save(t=>{t.active=null});showDialoguePool();const a=active(),l=campaignLevel(a);$('training-resume').hidden=!a||a.phase==='done';$('training-resume-label').textContent=a?`${l?`闯关第${l.id}关 · ${l.monster}`:names[a.mode]} · ${a.battle?`答对${a.correct} · 答错${a.battle.wrong}`:`第 ${a.index+1}/10 题`}`:'';$('training-history').replaceChildren();for(const h of (state()?.history||[]).slice(-10).reverse()){const row=document.createElement('p');row.textContent=`${h.campaign?`守护战闯关第${h.campaign.levelId}关`:names[h.mode]} · ${h.mode==='follow'?(h.localOnly?'完成10次录音/跳过（未评测）':'旧版自行跟读记录'):`答对 ${h.correct}/${h.total}`} · ${new Date(h.at).toLocaleDateString('zh-CN')}`;$('training-history').append(row)}}
 const itemKey=w=>String(w.q||w.en).trim().toLowerCase();
 const dialoguePool=()=>{const units=new Set(sentencePool().map(s=>s.unit));return D.dialogues.filter(d=>units.has(d.unit))};
 function cycle(pool,count=10){const unique=[...new Map(pool.map(w=>[itemKey(w),w])).values()];if(!unique.length)return [];const out=[];while(out.length<count){const batch=C.shuffle(unique);if(out.length&&batch.length>1&&itemKey(batch[0])===itemKey(out.at(-1))){const swap=batch.findIndex(w=>itemKey(w)!==itemKey(out.at(-1)));[batch[0],batch[swap]]=[batch[swap],batch[0]]}out.push(...batch.slice(0,count-out.length))}return out}
 function showDialoguePool(){const pool=dialoguePool(),count=new Set(pool.map(itemKey)).size;let note=$('training-dialogue-pool');if(!note){note=document.createElement('p');note.id='training-dialogue-pool';note.className='note';$('training-scope').after(note)}note.hidden=!count;note.textContent=count?`对话练习：当前范围有 ${count} 组课本问答，全部练过后再循环复习。${count<10?'想练更多题，可在家长设置选择“上册全部”（15组）。':'答对10题获胜，答错累计10题落败。'}`:'';const a=active();if(a?.mode==='dialogue'&&a.phase!=='done'&&a.scope===scope()){const savedCount=new Set(a.items.map(itemKey)).size;if(savedCount<count)note.textContent+=` 上次对战保留 ${savedCount} 组原题；重新选择游戏可使用补齐的题库。`}}
 function showDialogueCycle(a){if(a.mode!=='dialogue')return;const label=document.createElement('small');label.className='training-pool-progress';const l=campaignLevel(a);if(l){const w=a.items[a.index];label.textContent=`${window.BattleCampaign.labels[w.kind]}${w.timed?' · ⚡限时':''} · 奖励×${l.rewardMultiplier}`}else{const count=new Set(a.items.map(itemKey)).size,cycleNumber=Math.floor(a.index/count)+1;label.textContent=`${count}组问答 · ${cycleNumber===1?'首轮练习':`第${cycleNumber}轮复习`}`}$('training-count').append(label)}
 function start(mode,options={}){if(!names[mode])return;if(options.campaign){const l=window.Progression?.level('battle',options.campaign.id??options.campaign.levelId);if(mode!=='dialogue'||!l||!window.Progression.canStart('battle',l.id)){C.toast('请先完成上一关并达到90%正确率。');return false}halt();window.BattleAudio?.unlock();const items=window.BattleCampaign.build(l);if(items.length!==20){C.toast('本关素材未准备完整，请稍后重试。');return false}if(!save(t=>{t.active={id:C.uid(),mode,scope:scope(),campaign:{kind:'battle',levelId:l.id},items,index:0,correct:0,remaining:l.seconds*1000,phase:'ready',submitted:'',ok:false,battle:{wrong:0,streak:0},storySeen:false,battlePlayed:[]}}))return false;render(true);return true}
 halt();window.BattleCampaign?.apply(null);if(mode==='dialogue')window.BattleAudio?.unlock();const sentence=mode==='dialogue'||mode==='translate'||(mode==='follow'&&$('follow-kind').value==='sentence'),sp=sentencePool();if(sentence&&!sp.length){C.toast('句子资料对应你拍的新版上册，请在家长设置选择“我的课本”上册或单元。');return}
 const wordPool=C.words(A.state.garden).map(w=>({en:w[0],zh:w[1]}));const pool=mode==='dialogue'?dialoguePool():sentence?sp:wordPool;
 const direction=$('translation-direction').value,hear=$('listening-kind').value;
 if(mode!=='dialogue'&&pool.length<10)C.toast(`当前范围有${pool.length}条素材，练完后会循环复习。`);
 const realmMode=['meaning','reaction'].includes(mode)&&!!window.WordRealm;const items=cycle(pool,mode==='dialogue'?20:10).map(w=>{const english=!realmMode&&(mode==='dialogue'||mode==='translate'&&direction==='zh-en'||(mode==='listening'||mode==='reaction')&&hear==='word');const expected=english?w.en:w.zh;const others=C.shuffle([...new Set((mode==='dialogue'?sp:pool).map(p=>english?p.en:p.zh).filter(x=>x!==expected))]).slice(0,3);return {...w,expected,options:C.shuffle([expected,...others]),english,direction,hear}});
 if(!items.length){C.toast('当前范围没有适用的练习。');return}if(!save(t=>{t.active={id:C.uid(),mode,scope:scope(),items,index:0,correct:0,remaining:10000,phase:'ready',submitted:'',ok:false,...(mode==='dialogue'?{battle:{wrong:0,streak:0},storySeen:false,battlePlayed:[]}:{}),...(mode==='follow'?{followLocal:true,recorded:false}:{})};if(realmMode)t.active.realm=WordRealm.createState(t.active)}))return;render(true)}
 function audio(text,file){
  const token=++audioEpoch;C.stopSpeech();media.pause();
  const finish=ok=>{if(token!==audioEpoch)return;if(ok&&active()?.realm)WordRealm.audioStatus('');if(!ok){$('training-audio-note').textContent='未能播放，请点“听示范”重试。';window.WordRealm?.audioStatus?.('单词声音未播放，请点“听单词”重试。')}if(active()?.mode==='dialogue')window.BattleAudio?.englishEnd();if(active()?.phase==='ready'&&(active().campaign&&active().items[active().index].timed||active().realm&&active().mode==='reaction'))beginTimer()};
  media.onended=()=>finish(true);media.onerror=()=>finish(false);
  if(file){media.src=file;media.play().catch(()=>finish(false))}else C.speak(text,finish)
 }
 function narrationContext(a=active()){
  return {roundId:a?.id,playedKeys:a?.battlePlayed||[],onMark:key=>{
   if(!/^vo_[a-z_]+$/.test(key)||active()?.id!==a?.id)return;
   save(t=>{const r=t.active;r.battlePlayed??=[];if(!r.battlePlayed.includes(key))r.battlePlayed.push(key)})
  }}
 }
 function enterBattle(a){
  const n=narrationContext(a),stats=battleStats(a);window.BattleAudio?.enter(stats,n.roundId,n.playedKeys,n.onMark);
  window.BattleCampaign?.apply(a);if(campaignLevel(a)?.videoAvailable===false){window.BattleFilm?.stop();return}
  window.BattleFilm?.init(document.getElementById('dialogue-battle'));
  if(a.phase==='done'&&stats.terminal){
   const ending=stats.terminal==='won'?'victory_shield':'defeat_retry';
   if(!(BattleFilm.status.held&&BattleFilm.status.kind===ending))window.BattleFilm?.play(ending)
  }else window.BattleFilm?.idle()
 }
 function performBattleAttack(a){
  const stats=battleStats(active()),key=a.id+':'+a.index,epoch=battlePlaybackEpoch,special=a.ok&&stats.streak>0&&stats.streak%5===0;
  const kind=special?'special_light':a.ok?'hero_attack':'monster_attack',n=narrationContext(a);
  const current=()=>battlePlaybackEpoch===epoch&&active()?.id+':'+active()?.index===key&&active()?.phase==='answered';
  let started=false;
  const sound=(cues,durationMs)=>{if(started||!current())return;started=true;window.BattleAudio?.event(a.ok,stats,{...n,cueSeconds:cues,durationMs,terminalDelayMs:stats.terminal?durationMs:0})};
  window.DialogueBattle?.hit(a.ok,stats);
  const fallback=special?1750:1150;
  if(campaignLevel(a)?.videoAvailable===false){sound({impact:special ? .56 : .47,beam:.35},fallback);holdNextForAttack(key,fallback);return}
  const film=window.BattleFilm?.play(kind,{onStart:info=>sound(info.cueSeconds,info.durationMs)});
  const attackDuration=film?.durationMs||fallback;
  const endingDuration=stats.terminal?5100:0;
  holdNextForAttack(key,Math.min(22000,attackDuration+endingDuration+6500));
  if(!film){sound({impact:special ? .56 : .47,beam:.35},fallback);holdNextForAttack(key,fallback);return}
  Promise.resolve(film.promise).then(async result=>{
   if(!current())return;
   if(result?.cancelled){
    window.BattleAudio?.stop();const context=narrationContext(active());window.BattleAudio?.enter(stats,context.roundId,context.playedKeys,context.onMark);
    if(stats.terminal){const ending=window.BattleFilm?.play(stats.terminal==='won'?'victory_shield':'defeat_retry');if(ending)await ending.promise}else window.BattleFilm?.idle();
    if(current())unlockNext(key);return
   }
   if(!result?.played){
    window.DialogueBattle?.hit(a.ok,stats);sound({impact:special ? .56 : .47,beam:.35},fallback);
    holdNextForAttack(key,fallback);return
   }
   if(!started)sound({impact:special ? .56 : .47,beam:.35},fallback);
   if(stats.terminal){const end=window.BattleFilm?.play(stats.terminal==='won'?'victory_shield':'defeat_retry',{hold:true});if(end)await end.promise}
   else window.BattleFilm?.idle();
   if(current())unlockNext(key)
  }).catch(()=>{if(current()){sound({impact:special ? .56 : .47,beam:.35},fallback);unlockNext(key)}})
 }
 function unlockNext(key){const a=active();if(a?.mode!=='dialogue'||a.phase!=='answered'||a.id+':'+a.index!==key)return;clearTimeout(nextUnlockTimer);nextUnlockTimer=null;window.BattleCampaign?.apply(a);$('training-next').disabled=false;document.querySelector('.training-card').classList.remove('battle-resolving')}

 function listen(){const a=active();if(!a||a.phase==='done')return;const w=a.items[a.index];if(a.phase==='ready'&&(a.campaign&&w.timed||a.realm&&a.mode==='reaction')){if(timer){const left=Math.max(0,Math.min(timeLimit(a),Math.ceil(deadline-performance.now())));clearInterval(timer);timer=null;save(t=>{t.active.remaining=left})}$('training-timer').textContent=`⚡ 听完后 ${Math.ceil(active().remaining/1000)} 秒`;if(a.realm)WordRealm.setClock(active().remaining)}if(a.mode==='dialogue'){window.BattleAudio?.unlock();window.BattleAudio?.question()}if(a.realm&&a.phase==='ready')WordRealm.audioStatus(a.mode==='reaction'?'正在听示范，计时暂停…':'正在播放单词…');WordAudio.unlock();audio(a.campaign?w.hearText:a.mode==='dialogue'?w.q:w.en,a.campaign?(w.kind==='dialogue'?w.qAudio:w.audio):a.mode==='dialogue'?w.qAudio:w.audio)}
 function decorateDialogue(a,w){const dialogue=a.mode==='dialogue',card=document.querySelector('.training-card'),button=$('training-listen'),l=campaignLevel(a);card.classList.toggle('battle-complete',dialogue&&a.phase==='done');button.textContent=dialogue?'🔊 重听':'🔊 听示范';button.setAttribute('aria-label',dialogue?'重新听本题英语':'听英语示范');if(dialogue){window.DialogueBattle?.setDialogue({question:l?window.BattleCampaign.question(w):w.q,context:w.context,answer:w.en,translation:w.zh,phase:a.phase,ok:a.ok,terminal:battleStats(a).terminal,key:a.id+':'+a.index+':'+a.phase,story:l?window.BattleCampaign.story(a,w):window.BattleStory?.scene(battleStats(a),w)});const speaker=document.querySelector('.battle-dialogue-name');if(l&&a.phase==='ready'&&speaker)speaker.textContent=`${l.monster} · ${window.BattleCampaign.labels[w.kind]}`;const box=document.querySelector('.battle-dialogue');if(box){let controls=box.querySelector('.battle-dialogue-controls');if(!controls){controls=document.createElement('div');controls.className='battle-dialogue-controls';box.append(controls)}controls.append(button)}}else card.insertBefore(button,card.querySelector('.training-record-actions'))}
 function beginTimer(){const a=active(),w=a?.items[a.index],timed=a?.mode==='reaction'||!!(a?.campaign&&w?.timed);if(!a||a.phase!=='ready'||!timed||document.hidden||document.querySelector('.battle-intro-active'))return;clearInterval(timer);deadline=performance.now()+a.remaining;const key=a.id+':'+a.index;const tick=()=>{if(active()?.id+':'+active()?.index!==key||active()?.phase!=='ready'){clearInterval(timer);timer=null;return}const ms=deadline-performance.now();$('training-timer').textContent=`⚡ ${Math.max(0,Math.ceil(ms/1000))} 秒`;if(a.realm)WordRealm.setClock(ms);if(ms<=0){clearInterval(timer);timer=null;answer('__timeout__')}};tick();if(active()?.phase==='ready')timer=setInterval(tick,100)}
 function openStory(a){if(a.mode!=='dialogue'||a.phase!=='ready'||a.storySeen!==false||!window.BattleStory?.intro||!window.DialogueBattle?.showIntro)return false;const key=a.id,l=campaignLevel(a);document.querySelector('.training-card').classList.add('battle-intro-active');window.DialogueBattle.showIntro({lines:l?window.BattleCampaign.intro(a):window.BattleStory.intro,onStep:index=>{if(!l||l.videoAvailable){window.BattleAudio?.intro(index);if(index===0)window.BattleFilm?.play('intro_city',{onEnd:()=>{if(DialogueBattle.state.intro)window.BattleFilm?.idle()}});else window.BattleFilm?.idle()}},onFinish:()=>{const current=active();if(current?.id!==key||current.mode!=='dialogue'||current.phase!=='ready')return;save(t=>{t.active.storySeen=true});document.querySelector('.training-card').classList.remove('battle-intro-active');window.BattleAudio?.stop();window.BattleFilm?.stop();enterBattle(current);const w=active().items[active().index];decorateDialogue(active(),w);if(!current.campaign||w.kind!=='meaning')listen();if(!current.campaign||!w.timed||w.kind==='meaning')beginTimer()}});return true}
 function holdNextForAttack(key,duration=1150){const button=$('training-next');button.disabled=true;document.querySelector('.training-card').classList.add('battle-resolving');nextUnlockTimer=setTimeout(()=>unlockNext(key),duration)}
 function render(autoplay=false){halt();if(active()?.mode==='dialogue'&&!active().battle&&active().phase!=='done')save(t=>{const r=t.active;r.battle={wrong:r.index+(r.phase==='ready'?0:1)-r.correct,streak:0};r.items.push(...cycle(r.items));const pool=sentencePool();r.items.forEach((w,i)=>{if(i===r.index&&r.phase==='answered')return;const others=C.shuffle([...new Set(pool.map(p=>p.en).filter(x=>x!==w.expected))]).slice(0,3);w.options=C.shuffle([w.expected,...others])})});const a=active();if(!a)return home();focus(true);$('training-home').hidden=true;$('training-round').hidden=false;const w=a.items[a.index],answered=a.phase!=='ready',l=campaignLevel(a);document.body.classList.toggle('training-realm',!!a.realm);$('training-realm-scene').hidden=!a.realm;$('training-game-scene').hidden=a.mode==='dialogue'||!!a.realm;$('training-battle-scene').hidden=a.mode!=='dialogue';window.TrainingQuest?.render({mode:a.mode,index:a.index,correct:a.correct,answered,ok:a.ok,skipped:a.submitted==='__skipped__',recorded:a.recorded});window.DialogueBattle?.render(battleStats(a));document.querySelector('.training-card').classList.toggle('reviewing',answered);document.body.classList.toggle('training-dialogue',a.mode==='dialogue');$('training-count').textContent=l?`第${l.id}关 · ${l.scene} · 第${a.index+1}题`:a.battle?`奥特曼对战 · 第${a.index+1}题`:a.realm?`穿越星门 · ${a.mode==='reaction'?'限时':'普通'} · ${a.index+1}/10`:`${names[a.mode]} · ${a.index+1}/10`;$('training-audio-note').textContent='';$('training-record').textContent='🎙️ 按住跟读';$('training-choices').replaceChildren();$('training-review').hidden=!answered;$('training-next').hidden=!answered;$('training-next').textContent=a.battle&&(a.correct>=10||a.battle.wrong>=10)?'查看对战结果 →':!a.battle&&a.index===9?'查看收获 →':'下一题 →';$('training-record').hidden=a.mode!=='follow'||answered;$('training-self').hidden=a.mode!=='follow'||answered;$('training-self').textContent='跳过本题（不计正确） →';$('training-playback').hidden=true;$('training-listen').hidden=a.mode==='meaning';$('training-timer').hidden=!(a.mode==='reaction'||l&&w.timed)||answered;if(l&&w.timed&&!answered)$('training-timer').textContent=`⚡ ${Math.ceil(a.remaining/1000)} 秒`;
 $('training-prompt').textContent=l?window.BattleCampaign.question(w):a.mode==='follow'?w.en:a.mode==='meaning'?w.en:a.mode==='translate'?(w.direction==='zh-en'?w.zh:w.en):a.mode==='dialogue'?`听问句，选合适的回答。${w.context}`:a.mode==='reaction'?'10秒内选对，点亮闪电！':'听英文，选'+(w.hear==='word'?'对应单词':'中文意思');
 $('training-description').textContent=a.mode==='follow'?w.zh: a.mode==='translate'?'选择对应翻译':a.mode==='meaning'?'把这个英文与中文意思配成一对':'';
 if(a.mode!=='follow')for(const option of w.options){const b=document.createElement('button');b.type='button';b.className='training-choice';b.textContent=option;if(a.mode==='dialogue'){b.dataset.choice='ABCD'[w.options.indexOf(option)];b.setAttribute('aria-label',b.dataset.choice+'. '+option);if(answered&&option===a.submitted)b.classList.add('selected')}b.disabled=answered;b.onclick=()=>answer(option);if(answered){if(option===w.expected)b.classList.add('correct');if(option===a.submitted&&!a.ok)b.classList.add('incorrect')} $('training-choices').append(b)}
 $('training-review').textContent=answered?(a.mode==='follow'?(a.followLocal?`已跳过（不计正确）：${w.en} = ${w.zh}。录音留在本机，本题未做发音评测。`:`旧版自行跟读记录（未评测）：${w.en} = ${w.zh}`):`${a.ok?'✓ 答对':'✗ '+(a.submitted==='__timeout__'?'超时':'答错')} · 正确答案：${w.en} = ${w.zh}${a.mode==='dialogue'&&w.q?'；问句：'+w.q:''}`):'';
 showDialogueCycle(a);decorateDialogue(a,w);if(a.mode==='dialogue')enterBattle(a);
 if(a.realm){WordRealm.render(a,w);WordRealm.setClock(a.mode==='reaction'?a.remaining:null)}
 if(a.phase==='done'){focus(a.mode==='dialogue'||!!a.realm);document.body.classList.toggle('training-dialogue',a.mode==='dialogue');$('training-prompt').textContent=a.battle?(a.correct>=10?'光的力量，战胜怪兽！':'怪兽获胜，下次再挑战！'):'本轮训练完成';$('training-description').textContent=a.mode==='follow'?(a.followLocal?'本轮跟读已结束。录音和跳过不计正确、不发奖励；可重新选择游戏。':'旧版练习已结束，原奖励保留。'):l?`答对${a.correct}，累计受击${a.battle.wrong}；正确率${Math.round(a.correct/(a.index+1)*100)}%。${a.correct>=10&&a.correct/(a.index+1)>=.9?(l.id<10?'下一关已解锁！':'全部关卡完成！'):'达到90%正确率并获胜可解锁下一关。'}奖励倍率×${l.rewardMultiplier}。`:a.battle?`答对 ${a.correct}，累计受击 ${a.battle.wrong}；奖励水滴已存入花园。`:`答对 ${a.correct}/10，获得 ${a.correct} 个水滴${a.correct>=9?'和1个太阳':''}。`; $('training-choices').replaceChildren();$('training-review').hidden=true;$('training-next').textContent=l?'返回闯关地图 →':'回训练首页 →';$('training-listen').hidden=true;return}

 if(openStory(a))return;
 if(autoplay&&!answered&&(['listening','reaction','dialogue','follow'].includes(a.mode)||a.realm)&&(!l||w.kind!=='meaning'))listen();if(!answered&&!(a.realm&&a.mode==='reaction'&&autoplay)&&(!l||!w.timed||w.kind==='meaning'||!autoplay))beginTimer()}
 function answer(value){const a=active();if(!a||a.phase!=='ready'||a.mode==='follow'&&value!=='__skipped__')return false;const ok=value===a.items[a.index].expected;halt();if(!save((t,g)=>{const r=t.active;if(r.id!==a.id||r.index!==a.index||r.phase!=='ready')return false;r.phase='answered';r.submitted=value;r.ok=ok;if(r.realm){const rr=r.realm,room=i=>i<3?1:i<6?2:3;if(!rr.marks.some(m=>m.index===r.index))rr.marks.push({index:r.index,ok,shielded:!ok&&rr.upgrades.shield>rr.marks.filter(m=>m.shielded&&room(m.index)===rr.room).length});rr.shotIndex=r.index}if(r.mode==='follow')r.followLocal=true;if(r.battle){r.storySeen=true;if(ok)r.battle.streak++;else{r.battle.wrong++;r.battle.streak=0}}if(ok){r.correct++;g.water+=campaignLevel(r)?.rewardMultiplier||1}}))return false;if(a.mode!=='follow'&&a.mode!=='dialogue')C.sound(ok?'drop':'miss');render();if(a.battle){performBattleAttack(active())}else if(!a.realm)window.TrainingQuest?.hit(ok,{mode:a.mode,index:a.index,correct:active().correct,skipped:value==='__skipped__'});return ok}
 function completeFollow(){const a=active();if(a?.mode!=='follow'||a.phase!=='ready')return;answer('__skipped__')}
 function battleStats(a=active()){return {correct:a?.correct||0,wrong:a?.battle?.wrong||0,streak:a?.battle?.streak||0,terminal:a?.battle?(a.correct>=10?'won':a.battle.wrong>=10?'lost':null):null}}
 function next(){const a=active();if(!a||a.phase==='ready')return;if(a.realm&&!WordRealm.beforeNext(a))return;if(a.phase==='done'){if(a.campaign){home();window.Progression?.show('campaign');return}return home()}
 if(!save((t,g,root)=>{const r=t.active,terminal=r.battle?(r.correct>=10||r.battle.wrong>=10):r.index===9,l=campaignLevel(r);if(terminal){r.phase='done';if(!t.history.some(h=>h.id===r.id)){
  if(l&&!window.Progression.record(root,{kind:'battle',levelId:l.id,id:r.id,correct:r.correct,total:r.index+1,outcome:r.correct>=10?'won':'lost'}))return false;
  t.history.push({id:r.id,mode:r.mode,at:new Date().toISOString(),correct:r.correct,total:r.index+1,...(r.campaign?{campaign:{...r.campaign}}:{}),...(r.followLocal?{localOnly:true}:{})});
  if(r.mode!=='follow'){if(r.correct/(r.index+1)>=.9&&(!l||r.correct>=10))g.suns+=l?.rewardMultiplier||1;if(!r.battle)g.history.push({id:r.id,mode:names[r.mode],at:new Date().toISOString(),correct:r.correct,total:10})}
 }}else{r.index++;r.phase='ready';r.remaining=timeLimit(r);r.submitted='';r.ok=false;r.recorded=false;if(r.realm){r.realm.questionIndex=r.index;r.realm.room=r.index<3?1:r.index<6?2:3;r.realm.selected='';r.realm.pendingChest=0;r.realm.shotIndex=-1}if(r.mode==='follow')r.followLocal=true}}))return;render(true)
 }
 function chooseAnother(){pause();if(!save(t=>{t.active=null}))return;home();$('training-modes').scrollIntoView({block:'start',behavior:'smooth'});C.toast('请选择新的游戏，已经获得的奖励和完整记录都保留。')}
 async function microphone(){
 if(record?.state==='recording'||micPending)return;
 if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){$('training-audio-note').textContent='这个浏览器不支持录音。可以反复听示范，或跳过（不计正确）。';return}
 const wanted=pressWanted;halt();pressWanted=wanted;const epoch=recordEpoch;const key=active()?.id+':'+active()?.index;micPending=true;
 let captured=null;
 try{captured=await navigator.mediaDevices.getUserMedia({audio:true});if(epoch!==recordEpoch||!pressWanted||active()?.phase!=='ready'||document.hidden){captured.getTracks().forEach(t=>t.stop());if(!pressWanted&&epoch===recordEpoch)$('training-audio-note').textContent='权限已准备。请再次按住麦克风跟读，松开结束。';return}
 stream=captured;const chunks=[];record=new MediaRecorder(stream);const thisRecord=record;record.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};
 record.onstop=()=>{captured.getTracks().forEach(t=>t.stop());if(stream===captured)stream=null;if(epoch!==recordEpoch||!chunks.length||key!==active()?.id+':'+active()?.index)return;recordURL=URL.createObjectURL(new Blob(chunks,{type:thisRecord.mimeType}));playback.src=recordURL;save(t=>{t.active.recorded=true});$('training-playback').hidden=false;$('training-record').textContent='🎙️ 按住再读';$('training-audio-note').textContent='录音完成，尚未评测。可以回听、重录或跳过；不会自动判为正确。';window.TrainingQuest?.render({mode:'follow',index:active().index,correct:active().correct,recorded:true})};
 record.start();$('training-record').textContent='🔴 松开结束';$('training-audio-note').textContent='正在收音…';holdTimer=setTimeout(releaseMic,15000);
 }catch{captured?.getTracks().forEach(t=>t.stop());if(stream===captured)stream=null;if(epoch===recordEpoch&&key===active()?.id+':'+active()?.index){record=null;pressWanted=false;clearTimeout(holdTimer);$('training-record').textContent='🎙️ 按住跟读';$('training-audio-note').textContent=captured?'录音未能启动，麦克风已关闭。请重试或跳过（不计正确）。':'没有取得麦克风权限。请允许后按住重试，或跳过（不计正确）。'}}finally{micPending=false}
 }
 function pressMic(e){if(e?.button!==undefined&&e.button!==0||active()?.mode!=='follow'||active()?.phase!=='ready')return;e?.preventDefault();pressWanted=true;try{if(e?.pointerId!==undefined)$('training-record').setPointerCapture(e.pointerId)}catch{}microphone()}
 function releaseMic(){pressWanted=false;clearTimeout(holdTimer);if(record?.state==='recording')record.stop()}
 // Battle sound preferences remain local and are independent of learning progress.
 for(const [id,key] of [['battle-music','music'],['battle-sound-effects','effects'],['battle-voices','voices']]){
  const input=$(id);if(!input)continue;input.checked=window.BattleAudio?.settings?.[key]!==false;
  input.addEventListener('change',()=>window.BattleAudio?.setSettings({[key]:input.checked}))
 }
 $('training-battle-scene').innerHTML=DialogueBattle.markup();$('training-game-scene').innerHTML=TrainingQuest.markup();
 $('training-realm-scene').innerHTML=WordRealm.markup();
 WordRealm.configure({mount:$('training-realm-scene'),getActive:active,saveRealm:(value,id)=>save(t=>{if(t.active?.id!==id)return false;t.active.realm=value}),onAnswer:answer,onNext:next,onExit:home,onHear:listen});
 const cards=[['listening','🎧','寻宝岛：听英文寻找宝藏'],['follow','🎙️','声音精灵：按住跟读、回听'],['meaning','🌀','穿越星门：词义配对、探索与宝箱'],['dialogue','💬','奥特曼：对话打怪兽'],['translate','🌐','修桥任务：中译英 / 英译中']];
 $('training-modes').innerHTML=cards.map(([key,icon,description])=>`<button class="training-mode" data-training="${key}"><span>${icon}</span><strong>${names[key]}</strong><small>${description}</small></button>`).join('');
 const shooting=document.createElement('button');shooting.type='button';shooting.className='training-mode';shooting.id='training-shooter';shooting.innerHTML='<span>✧</span><strong>单词守卫</strong><small>房间射击：三至五年级词库、无限关卡</small>';shooting.onclick=()=>ShooterCampaign.open();$('training-modes').append(shooting);
 document.querySelectorAll('[data-training]').forEach(b=>b.onclick=()=>start(b.dataset.training==='meaning'&&$('realm-difficulty').value==='timed'?'reaction':b.dataset.training));$('training-continue').onclick=()=>{if(!active()?.campaign&&active()?.scope!==scope()){home();C.toast('词库已改变，请重新开始训练。')}else render(true)};$('training-restart').onclick=chooseAnother;$('training-switch').onclick=chooseAnother;$('training-exit').onclick=home;$('training-next').onclick=next;$('training-listen').onclick=listen;$('training-record').onpointerdown=pressMic;$('training-record').onpointerup=releaseMic;$('training-record').onpointercancel=releaseMic;$('training-record').onkeydown=e=>{if([' ','Enter'].includes(e.key)&&!e.repeat)pressMic(e)};$('training-record').onkeyup=e=>{if([' ','Enter'].includes(e.key))releaseMic()};$('training-playback').onclick=()=>playback.play().catch(()=>C.toast('回听未开始，请再点一次。'));$('training-self').onclick=completeFollow;
 document.addEventListener('pointerup',releaseMic);document.addEventListener('pointercancel',releaseMic);
 document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});window.addEventListener('pagehide',pause);
 window.EnglishTraining={home,start,answer,next,pause,render,completeFollow,sentencePool,get active(){return active()},chooseAnother,pressMic,releaseMic,get recordStatus(){return {recording:record?.state==='recording',hasClip:!!recordURL}},get feedbackAudio(){return story},get media(){return media}};
})();
