/* Original word-meaning adventure. No source or assets from vocab-roguelike.
   The host owns questions, scores, water, suns and the saved round. */
(() => {
 'use strict';
 const upgrades={
  boots:{name:'疾风靴',icon:'➤',description:'走路更快，身后留下金色风痕。'},
  prism:{name:'棱镜弹',icon:'✧',description:'双束弹道与彩虹冲击波，让每次命中更耀眼。'},
  shield:{name:'守护盾',icon:'⬡',description:'每间房抵挡一次反击；错题仍保留，方便复习。'}
 };
 const rooms=[{name:'青苔遗迹',scene:3,monster:3,color:'#76e5c4',story:'词语结晶被怪物锁住了。找出它的意思，恢复遗迹的光。'},
  {name:'沙丘试炼',scene:7,monster:7,color:'#ffc677',story:'风沙打散了词语。带着宝箱里的装备，继续寻找正确词义。'},
  {name:'星门圣殿',scene:8,monster:8,color:'#a7d0ff',story:'最后一道星门等待点亮。每理解一个词，就让回家的路更亮。'}];
 let hooks={},mount=null,a=null,w=null,r=null,savedRealm=null,epoch=0,walkEpoch=0,frames=new Set(),timers=new Set(),observer=null,position=.22,busy=false,paused=false,clock=null,lastRenderedKey='';
 const copy=value=>JSON.parse(JSON.stringify(value)),clamp=(n,min,max)=>Math.min(max,Math.max(min,n));
 const qkey=()=>a?`${a.id}:${a.index}`:'',roomFor=index=>index<3?1:index<6?2:3;
 const node=id=>mount?.querySelector(`[data-realm="${id}"]`);
 const reduced=()=>window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;
 const asset=path=>`${hooks.assetBase||''}${path}`;
 const explorer=`<svg viewBox="0 0 100 140" aria-hidden="true"><defs><linearGradient id="realm-cloak" x2="1" y2="1"><stop stop-color="#78c9a5"/><stop offset="1" stop-color="#226c63"/></linearGradient></defs><ellipse cx="51" cy="132" rx="30" ry="7" fill="#071e1e66"/><path d="M34 96 25 132Q34 141 42 129L52 106 61 133Q71 140 80 130L68 92Z" fill="#375448"/><path d="M17 64Q49 47 82 64L91 114Q54 136 9 113Z" fill="url(#realm-cloak)" stroke="#c5f1c7" stroke-width="2"/><path d="M48 65 29 119 68 119 58 65Z" fill="#f7e4b7"/><ellipse cx="50" cy="45" rx="25" ry="27" fill="#ffd7aa"/><path d="M20 38 33 11Q50 0 68 11L84 38Q57 50 20 38Z" fill="#277c67" stroke="#abdd92" stroke-width="2"/><path d="M18 35Q50 48 85 35L84 45Q51 57 16 45Z" fill="#386452"/><path d="M44 18 65 28 46 35Z" fill="#f6cd77"/><ellipse cx="42" cy="53" rx="3" ry="4" fill="#394339"/><ellipse cx="64" cy="53" rx="3" ry="4" fill="#394339"/><path d="M48 65Q54 69 60 63" fill="none" stroke="#bb7a56" stroke-width="2"/><path d="M20 78 5 100 15 108 31 90" fill="#a8d6b1"/><path d="M78 77 93 96 83 104 68 89" fill="#a8d6b1"/><path d="M78 91 95 82" stroke="#b68542" stroke-width="5" stroke-linecap="round"/><circle cx="96" cy="80" r="8" fill="#fff3a2" stroke="#ddaa4d" stroke-width="3"/></svg>`;
 const chestSVG=`<svg viewBox="0 0 120 95" aria-hidden="true"><defs><linearGradient id="realm-chest-gold" x2="0" y2="1"><stop stop-color="#ffef9a"/><stop offset="1" stop-color="#c88835"/></linearGradient></defs><path d="M18 45Q19 13 60 12T102 45Z" fill="#b66f39" stroke="#fff2b5" stroke-width="3"/><path d="M16 44 103 44 103 85 16 85Z" fill="#955734" stroke="#e9bd6c" stroke-width="3"/><path d="M28 18 29 85M90 18 90 85M16 49 103 49" stroke="url(#realm-chest-gold)" stroke-width="9"/><path d="M51 42 69 42 69 63 51 63Z" fill="#ffd36f" stroke="#744c29" stroke-width="2"/><circle cx="60" cy="52" r="3" fill="#72462c"/></svg>`;
 function markup(){return `<section class="word-realm" aria-label="词域探险：理解词义，选择弹药射击怪物">
  <header class="realm-hud"><div class="realm-brand"><small>WORD REALM</small><strong data-realm="title">词域探险</strong></div><div class="realm-route" data-realm="route" aria-label="房间进度"></div><div class="realm-health"><span>护心 <b data-realm="hp">10</b></span><div role="progressbar" aria-valuemin="0" aria-valuemax="10" aria-label="冒险者护心" data-realm="health"><i></i></div></div><button type="button" class="realm-exit" data-realm="exit" aria-label="保存并返回">返回</button></header>
  <section class="realm-arena" data-realm="arena" aria-label="可以点地面移动；选好弹药后点英文怪物发射">
   <div class="realm-scene" data-realm="scene" aria-hidden="true"></div><div class="realm-scene-shade" aria-hidden="true"></div><div class="realm-ground" aria-hidden="true"></div>
   <div class="realm-room-sign"><span data-realm="room-name"></span><small data-realm="count"></small></div><p class="realm-story" data-realm="story"></p>
   <div class="realm-path-mark" data-realm="path" hidden aria-hidden="true"></div><div class="realm-hero" data-realm="hero"><div class="realm-hero-art"><img src="${asset('assets/realm-art/hero-v1.png')}" alt="" aria-hidden="true" decoding="async"></div><div class="realm-shield" data-realm="shield" hidden aria-hidden="true"></div><span class="realm-player-name">词语旅人</span></div>
   <button type="button" class="realm-monster" data-realm="monster" aria-label="选择中文弹药后射击这个英文怪物"><span class="realm-word" data-realm="word"></span><span class="realm-monster-body" data-realm="monster-art" aria-hidden="true"></span><i class="realm-monster-shadow" aria-hidden="true"></i></button>
   <canvas class="realm-canvas" data-realm="canvas" aria-hidden="true"></canvas><div class="realm-impact" data-realm="impact" aria-live="off"></div><div class="realm-shot-label" data-realm="shot-label" hidden></div><div class="realm-room-gate" aria-hidden="true"><span>✦</span></div>
  </section>
  <section class="realm-deck" aria-label="中文词义弹药与答题操作"><div class="realm-deck-heading"><div><strong>词义弹药</strong><small data-realm="instruction">选词义，再点怪物或发射</small></div><button type="button" data-realm="hear" class="realm-hear">听单词</button><span data-realm="clock" class="realm-clock" hidden></span></div><div class="realm-ammo" data-realm="ammo" role="group" aria-label="选择中文弹药"></div><div class="realm-feedback" data-realm="feedback" role="status"></div><div class="realm-actions"><button type="button" class="realm-fire" data-realm="fire">选择弹药后发射 <span>↗</span></button><button type="button" class="realm-next" data-realm="next" hidden>下一道星门 →</button></div><div class="realm-equipped" data-realm="equipped" aria-label="本局装备"></div></section>
  <section class="realm-chest-overlay" data-realm="chest" hidden aria-label="房间宝箱：选择一件升级装备"><div class="realm-chest-panel"><div class="realm-chest-art">${chestSVG}</div><small class="realm-chest-kicker">星门已经打开</small><h2 data-realm="chest-title">宝箱三选一</h2><p data-realm="chest-copy">选择装备，带进下一间房。</p><div class="realm-upgrades" data-realm="upgrade-options"></div><button type="button" class="realm-next" data-realm="chest-next" disabled>选好装备再出发 →</button></div></section>
 </section>`}
 function fresh(active){const done=active.phase==='ready'?active.index:active.index+1,currentWrong=active.phase!=='ready'&&!active.ok?1:0;return {version:1,room:roomFor(active.index),playerX:.22,questionIndex:active.index,selected:'',initialWrong:clamp(done-active.correct-currentWrong,0,10),marks:[],upgrades:{boots:0,prism:0,shield:0},chests:[],pendingChest:0,shotIndex:-1,shownShots:[]}}
 function configure(options={}){hooks={...hooks,...options};return window.WordRealm}
 function current(){return hooks.getActive?.()||window.EnglishTraining?.active||a}
 function commit(){if(!a||!r)return false;const value=copy(r);const save=hooks.saveRealm||((realm)=>window.Adventure?.update(root=>{if(root.training?.active?.id!==a.id)return false;root.training.active.realm=realm}));try{if(save(value,a.id)===false)throw new Error('realm save rejected');savedRealm=copy(value);return true}catch(error){r=copy(savedRealm||a.realm||fresh(a));if(node('feedback'))node('feedback').textContent='进度暂时无法保存，请重试这次操作。';return false}}
 function later(fn,ms){const id=setTimeout(()=>{timers.delete(id);fn()},ms);timers.add(id);return id}
 function animate(fn){const token=epoch,start=performance.now();let id;function tick(now){frames.delete(id);if(token!==epoch||paused)return;const more=fn(now-start);if(more){id=requestAnimationFrame(tick);frames.add(id)}}id=requestAnimationFrame(tick);frames.add(id)}
 function clearEffects(){epoch++;walkEpoch++;for(const id of frames)cancelAnimationFrame(id);frames.clear();for(const id of timers)clearTimeout(id);timers.clear();node('canvas')?.getContext('2d')?.clearRect(0,0,node('canvas').width,node('canvas').height);mount?.classList.remove('realm-firing','realm-hit','realm-hurt','realm-walking','realm-shield-hit','realm-deflected');node('shot-label')&&(node('shot-label').hidden=true);node('path')&&(node('path').hidden=true)}
 function ensure(){const found=hooks.mount?.querySelector?.('.word-realm')||document.querySelector('.word-realm');if(found===mount)return !!mount;observer?.disconnect();mount=found;if(!mount)return false;
  node('fire').onclick=fire;node('monster').onclick=event=>{event.stopPropagation();fire()};node('next').onclick=next;node('hear').onclick=()=>{if(a&&w){if(hooks.onHear)hooks.onHear(w.en);else window.GameCommon?.speak(w.en)}};node('exit').onclick=()=>{pause();(hooks.onExit||window.EnglishTraining?.home)?.()};node('chest-next').onclick=next;
  node('arena').addEventListener('pointerdown',event=>{if(event.target.closest('button')||busy||a?.phase!=='ready')return;const box=node('arena').getBoundingClientRect();moveTo(clamp((event.clientX-box.left)/box.width,.1,.72))});
  node('arena').addEventListener('keydown',event=>{if(a?.phase!=='ready'||busy)return;if(event.key==='ArrowLeft'||event.key==='ArrowRight'){event.preventDefault();moveTo(clamp(position+(event.key==='ArrowLeft'?-.13:.13),.1,.72))}});node('arena').tabIndex=0;
  observer=window.ResizeObserver?new ResizeObserver(fit):null;observer?.observe(node('arena'));return true
 }
 function fit(){if(!mount||!a)return;const box=node('arena').getBoundingClientRect();if(!box.width||!box.height)return;const room=rooms[roomFor(a.index)-1],cellW=2115/5,cellH=744/2,s=Math.max(box.width/cellW,box.height/cellH),col=room.scene%5,row=Math.floor(room.scene/5);node('scene').style.backgroundImage=`url("${asset('assets/progression-art/scenes-v1.png')}")`;node('scene').style.backgroundSize=`${2115*s}px ${744*s}px`;node('scene').style.backgroundPosition=`${-col*cellW*s+(box.width-cellW*s)/2}px ${-row*cellH*s+(box.height-cellH*s)/2}px`;
  const size=clamp(box.height*.43,62,185);node('monster').style.setProperty('--monster-size',`${size}px`);node('hero').style.width=`${clamp(box.height*.32,45,104)}px`;position=clamp(position,.1,.72);node('hero').style.left=`${position*100}%`;const canvas=node('canvas'),dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.ceil(box.width*dpr);canvas.height=Math.ceil(box.height*dpr);canvas.getContext('2d').setTransform(dpr,0,0,dpr,0,0)
 }
 function hp(){return clamp(10-r.initialWrong-r.marks.filter(mark=>!mark.ok&&!mark.shielded).length,0,10)}
 function shieldAvailable(room=roomFor(a.index)){return r.upgrades.shield>r.marks.filter(mark=>roomFor(mark.index)===room&&mark.shielded).length}
 function applyResult(){if(a.phase==='ready'||r.marks.some(mark=>mark.index===a.index))return;const shielded=!a.ok&&shieldAvailable();r.marks.push({index:a.index,ok:!!a.ok,shielded});r.shotIndex=a.index;commit()}
 function render(active,item){if(!active||!item)return stop();if(!ensure())return false;clearEffects();paused=false;busy=false;a=active;w=item;r=copy(active.realm||fresh(active));savedRealm=copy(r);if(r.questionIndex!==a.index){r.questionIndex=a.index;r.selected='';r.pendingChest=0;r.shotIndex=-1}r.room=roomFor(a.index);position=r.playerX;applyResult();commit();const room=rooms[r.room-1],answered=a.phase!=='ready';mount.style.setProperty('--realm-accent',room.color);mount.classList.toggle('realm-prism',r.upgrades.prism>0);mount.classList.toggle('realm-boots',r.upgrades.boots>0);mount.classList.toggle('realm-reviewed',answered);mount.classList.toggle('realm-correct',answered&&a.ok);mount.classList.toggle('realm-incorrect',answered&&!a.ok);mount.classList.toggle('realm-complete',a.phase==='done');node('title').textContent='词域探险';node('room-name').textContent=room.name;node('count').textContent=`第 ${a.index+1} / 10 道星门`;node('story').textContent=room.story;node('word').textContent=w.en;node('word').setAttribute('aria-label',`英文怪物：${w.en}`);node('monster').setAttribute('aria-label',`${w.en}。选择对应中文弹药后点击射击`);node('monster-art').style.backgroundImage=`url("${asset('assets/progression-art/monsters-v1.png')}")`;const monsterIndex=(room.monster+a.index%3)%10;node('monster-art').style.backgroundPosition=`${monsterIndex%5*25}% ${Math.floor(monsterIndex/5)*100}%`;node('monster').disabled=answered;node('hp').textContent=String(hp());node('health').setAttribute('aria-valuenow',String(hp()));node('health').querySelector('i').style.width=`${hp()*10}%`;node('shield').hidden=!shieldAvailable();node('route').replaceChildren();for(let n=1;n<=3;n++){const dot=document.createElement('span');dot.className=n===r.room?'current':n<r.room?'complete':'';dot.textContent=String(n);dot.setAttribute('aria-label',`房间${n}${n<r.room?'已通过':n===r.room?'正在探险':'等待进入'}`);node('route').append(dot)}
  node('ammo').replaceChildren();for(const option of w.options){const button=document.createElement('button');button.type='button';button.className='realm-ammo-chip';button.textContent=option;button.disabled=answered;button.setAttribute('aria-pressed',String(option===r.selected));if(option===r.selected)button.classList.add('selected');if(answered&&option===w.expected)button.classList.add('correct');if(answered&&option===a.submitted&&!a.ok)button.classList.add('incorrect');button.onclick=()=>pick(option);node('ammo').append(button)}
  node('instruction').textContent=answered?'首答已锁定，记住正确词义再出发':'选词义，再点怪物或发射';node('fire').hidden=answered;node('next').hidden=!answered;node('next').disabled=false;node('fire').disabled=!r.selected;node('fire').firstChild.textContent=r.selected?'发射词义弹 ':'选择弹药后发射 ';
  node('feedback').replaceChildren();if(answered){const label=document.createElement('small');label.textContent=a.ok?'✓ 命中词语结晶':a.submitted==='__timeout__'?'时间到了，再记一次':`你的弹药：${a.submitted}`;const answer=document.createElement('strong');answer.textContent=`${a.ok?'词义：':'正确词义：'}${w.en} = ${w.zh}`;node('feedback').append(label,answer);const mark=r.marks.find(mark=>mark.index===a.index);if(mark?.shielded){const hint=document.createElement('small');hint.textContent='护盾抵挡了反击；这题仍记录为答错。';node('feedback').append(hint)}}else{const tip=document.createElement('span');tip.textContent=r.selected?`已装填「${r.selected}」，瞄准英文怪物！`:'英文怪物挡住星门。挑选它的中文意思，给词语结晶充能。';node('feedback').append(tip)}
  node('next').textContent=a.phase==='done'?'回训练首页 →':a.index===9?'点亮星门，查看收获 →':a.index===2||a.index===5?'开启房间宝箱 ✦':'下一道星门 →';node('equipped').replaceChildren();for(const [key,n]of Object.entries(r.upgrades))if(n){const badge=document.createElement('span');badge.textContent=`${upgrades[key].icon} ${upgrades[key].name}${n>1?' ×'+n:''}`;node('equipped').append(badge)}node('equipped').hidden=!Object.values(r.upgrades).some(Boolean);
  if(a.phase==='done'){const rate=Math.round(a.correct/10*100);node('feedback').replaceChildren();const score=document.createElement('strong');score.textContent=`本轮 ${a.correct}/10 · 正确率 ${rate}%`;const reward=document.createElement('small');reward.textContent=`获得 ${a.correct} 个水滴${rate>=90?'、1 个太阳':''} · 回首页可选择其他游戏`;node('feedback').append(score,reward)}node('chest').hidden=!r.pendingChest;if(r.pendingChest)renderChest();fit();setClock(clock);lastRenderedKey=qkey();
  if(answered&&r.shotIndex===a.index&&!r.shownShots.includes(a.index)&&a.phase!=='done'){r.shownShots.push(a.index);commit();animateAttack(!!a.ok,r.marks.find(mark=>mark.index===a.index)?.shielded)}
  return true
 }
 function pick(value){if(!a||a.phase!=='ready'||busy||!w.options.includes(value))return false;r.selected=value;if(!commit())return false;for(const button of node('ammo').children){const chosen=button.textContent===value;button.classList.toggle('selected',chosen);button.setAttribute('aria-pressed',String(chosen))}node('feedback').textContent=`已装填「${value}」，瞄准英文怪物！`;node('fire').disabled=false;node('fire').firstChild.textContent='发射词义弹 ';return true}
 function fire(){if(!a||a.phase!=='ready'||busy)return false;if(!r.selected){node('feedback').textContent='先在下方选择一种中文弹药，再点击怪物。';node('ammo').classList.remove('realm-nudge');void node('ammo').offsetWidth;node('ammo').classList.add('realm-nudge');return false}const value=r.selected;r.shotIndex=a.index;if(!commit())return false;busy=true;const answer=hooks.onAnswer||window.EnglishTraining?.answer;if(!answer){busy=false;return false}answer(value);const latest=current();if(latest?.phase==='ready'){busy=false;node('feedback').textContent='这次选择未保存，请重新发射。';return false}if(lastRenderedKey!==`${latest.id}:${latest.index}`||a.phase==='ready')render(latest,latest.items?.[latest.index]||w);return true}
 function moveTo(target,finished){if(!a||!r)return;target=clamp(target,.1,.72);const from=position,dist=Math.abs(target-from),duration=reduced()?0:Math.max(100,dist*1050)/(1+r.upgrades.boots*.65);r.playerX=target;if(!commit()){finished?.();return}const walkToken=++walkEpoch;node('path').hidden=false;node('path').style.left=`${target*100}%`;mount.classList.add('realm-walking');if(!duration){position=target;node('hero').style.left=`${position*100}%`;mount.classList.remove('realm-walking');node('path').hidden=true;finished?.();return}animate(elapsed=>{if(walkToken!==walkEpoch)return false;const p=Math.min(1,elapsed/duration),ease=1-Math.pow(1-p,3);position=from+(target-from)*ease;node('hero').style.left=`${position*100}%`;if(p<1)return true;mount.classList.remove('realm-walking');node('path').hidden=true;finished?.();return false})}
 function coords(){const box=node('arena').getBoundingClientRect(),hero=node('hero').getBoundingClientRect(),monster=node('monster').getBoundingClientRect();return {width:box.width,height:box.height,hero:{x:hero.left-box.left+hero.width*.94,y:hero.top-box.top+hero.height*.10},monster:{x:monster.left-box.left+monster.width*.5,y:monster.top-box.top+monster.height*.45}}}
 function projectile(from,to,ok,prism,onEnd,effect=ok?'hit':'hurt'){const ctx=node('canvas').getContext('2d'),size=coords(),duration=reduced()?160:540,beam=prism>0,rays=prism>1?3:beam?2:1,colors=ok?['#fff9bc','#80fff0','#b4beff']:['#ffd291','#ff9a80','#ffceaa'];animate(elapsed=>{const t=Math.min(1,elapsed/duration);ctx.clearRect(0,0,size.width,size.height);const x=from.x+(to.x-from.x)*t,y=from.y+(to.y-from.y)*t-Math.sin(t*Math.PI)*(beam?12:26);for(let ray=0;ray<rays;ray++){const offset=(ray-(rays-1)/2)*12,grad=ctx.createLinearGradient(from.x,from.y,x,y);grad.addColorStop(0,'#b7ffff00');grad.addColorStop(.6,colors[2]);grad.addColorStop(1,colors[0]);ctx.strokeStyle=grad;ctx.lineWidth=beam?4:3;ctx.beginPath();ctx.moveTo(from.x,from.y+offset);ctx.quadraticCurveTo((from.x+x)/2,Math.min(from.y,y)-10,x,y+offset);ctx.stroke();ctx.shadowBlur=20;ctx.shadowColor=colors[1];ctx.fillStyle=colors[0];ctx.beginPath();ctx.arc(x,y+offset,beam?5:7,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}if(t<1)return true;impact(to,ok,prism,onEnd,effect);return false})}
 function impact(point,ok,prism,onEnd,effect=ok?'hit':'hurt'){const ctx=node('canvas').getContext('2d'),size=coords(),duration=reduced()?100:520,particles=Array.from({length:prism?54:30},(_,i)=>({angle:i*2.399963,speed:40+(i%9)*15,color:ok?['#fff3a2','#84fff0','#c4a9ff'][i%3]:['#ffc477','#ff9983','#fff0bd'][i%3]})),effectClass=effect==='shield'?'realm-shield-hit':effect==='deflect'?'realm-deflected':effect==='hit'?'realm-hit':'realm-hurt';mount.classList.add(effectClass);node('impact').textContent=effect==='shield'?'护盾抵挡':effect==='deflect'?'词义未匹配':ok?'词义命中！':'再记一次';node('impact').style.left=`${point.x}px`;node('impact').style.top=`${point.y}px`;animate(elapsed=>{const t=elapsed/duration;ctx.clearRect(0,0,size.width,size.height);for(const p of particles){ctx.globalAlpha=Math.max(0,1-t);ctx.strokeStyle=p.color;ctx.lineWidth=3;const distance=p.speed*t,x=point.x+Math.cos(p.angle)*distance,y=point.y+Math.sin(p.angle)*distance+30*t*t;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-Math.cos(p.angle)*7,y-Math.sin(p.angle)*7);ctx.stroke()}ctx.globalAlpha=1;ctx.strokeStyle=ok?'#d6ffef':'#ffcb9d';ctx.lineWidth=4*(1-t);ctx.beginPath();ctx.arc(point.x,point.y,12+t*(prism?85:58),0,Math.PI*2);ctx.stroke();if(t<1)return true;ctx.clearRect(0,0,size.width,size.height);mount.classList.remove(effectClass);onEnd?.();return false})}
 function animateAttack(ok,shielded){busy=true;node('next').disabled=true;mount.classList.add('realm-firing');const key=qkey(),token=epoch;moveTo(.33,()=>{if(token!==epoch||key!==qkey())return;const points=coords();node('shot-label').hidden=false;node('shot-label').textContent=r.selected||a.submitted;node('shot-label').style.left=`${points.hero.x}px`;node('shot-label').style.top=`${points.hero.y-24}px`;projectile(points.hero,points.monster,ok,r.upgrades.prism,()=>{if(token!==epoch||key!==qkey())return;node('shot-label').hidden=true;if(ok){done();return}if(shielded){node('shield').hidden=false;projectile(points.monster,points.hero,false,0,()=>{node('shield').hidden=!shieldAvailable();done()},'shield')}else{projectile(points.monster,points.hero,false,0,done)}},ok?'hit':'deflect')});
  function done(){if(token!==epoch||key!==qkey())return;busy=false;mount.classList.remove('realm-firing');node('next').disabled=false}later(done,3200)
 }
 function openChest(){const completedRoom=a.index===2?1:2,nextRoom=completedRoom+1;let chest=r.chests.find(chest=>chest.room===completedRoom);if(!chest){chest={room:completedRoom,choice:''};r.chests.push(chest)}r.pendingChest=nextRoom;if(!commit())return false;node('chest').hidden=false;renderChest()}
 function renderChest(){const completedRoom=r.pendingChest-1,chest=r.chests.find(chest=>chest.room===completedRoom);node('chest-title').textContent=`${rooms[completedRoom-1].name} · 宝箱三选一`;node('chest-copy').textContent=chest?.choice?`「${upgrades[chest.choice].name}」已装上，准备进入${rooms[completedRoom].name}。`:'选择一件装备。升级会带进下一间房，本局只选一次。';node('upgrade-options').replaceChildren();for(const [key,upgrade]of Object.entries(upgrades)){const button=document.createElement('button');button.type='button';button.className='realm-upgrade';button.disabled=!!chest?.choice;button.classList.toggle('selected',chest?.choice===key);button.setAttribute('aria-pressed',String(chest?.choice===key));const icon=document.createElement('span');icon.className='realm-upgrade-icon';icon.textContent=upgrade.icon;const texts=document.createElement('span'),title=document.createElement('strong'),description=document.createElement('small');title.textContent=upgrade.name;description.textContent=upgrade.description;texts.append(title,description);button.append(icon,texts);button.onclick=()=>chooseUpgrade(key);node('upgrade-options').append(button)}node('chest-next').disabled=!chest?.choice;node('chest-next').textContent=chest?.choice?`进入${rooms[completedRoom].name} →`:'选好装备再出发 →'}
 function chooseUpgrade(key){const chest=r?.chests.find(chest=>chest.room===r.pendingChest-1);if(!chest||chest.choice||!upgrades[key])return false;chest.choice=key;r.upgrades[key]++;const saved=commit();renderChest();if(!saved)node('chest-copy').textContent='装备尚未保存，请重新选择。';return saved}
 function beforeNext(active=a){if(!active?.realm)return true;if(!a||qkey()!==`${active.id}:${active.index}`)return false;if(active.phase==='ready'||busy)return false;if(active.phase!=='done'&&(active.index===2||active.index===5)){const completedRoom=active.index===2?1:2,chest=r.chests.find(chest=>chest.room===completedRoom);if(!chest?.choice){openChest();return false}r.pendingChest=0;if(!commit())return false;node('chest').hidden=true}return true}
 function next(){if(!beforeNext(current()))return false;pause();(hooks.onNext||window.EnglishTraining?.next)?.();return true}
 function animateReview(active,item=active?.items?.[active.index]){if(!active||active.phase==='ready')return false;if(a&&qkey()===`${active.id}:${active.index}`&&r.shownShots.includes(active.index))return true;return render(active,item)}
 function setClock(ms){clock=ms;if(!mount)return;node('clock').hidden=ms===null||ms===undefined||a?.phase!=='ready';if(!node('clock').hidden)node('clock').textContent=`⚡ ${Math.max(0,Math.ceil(ms/1000))}秒`}
 function audioStatus(text=''){if(!mount||a?.phase!=='ready')return;let label=node('audio-note');if(!text){label?.remove();return}if(!label){label=document.createElement('small');label.dataset.realm='audio-note';label.className='realm-audio-note';node('feedback').append(label)}label.textContent=text;label.setAttribute('role','status')}
 function pause(){paused=true;busy=false;clearEffects();if(node('next'))node('next').disabled=false}
 function stop(){pause();savedRealm=null;observer?.disconnect();observer=null;mount=null;a=null;w=null;r=null;lastRenderedKey='';clock=null}
 document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});window.addEventListener('pagehide',pause);
 window.WordRealm={markup,configure,createState:fresh,render,pick,fire,pause,stop,next,beforeNext,animateReview,setClock,audioStatus,chooseUpgrade,get state(){return r?copy(r):null},get status(){return {busy,paused,questionKey:qkey(),pendingFrames:frames.size}}};
})();
