(() => {
  'use strict';
  const C=GameCommon,{$,escape:E,int,validBase,validRound}=C;
  const fresh=()=>({version:1,app:'garden',settings:{pack:'nature'},custom:[],water:0,suns:0,growth:0,flowers:[],history:[],active:null});
  const validate=s=>validBase(s,'garden')&&int(s.water)&&int(s.suns)&&int(s.growth,99)&&Array.isArray(s.flowers)&&s.flowers.length<=10000&&s.flowers.every(f=>f&&int(f.variety,5)&&typeof f.at==='string'&&Number.isFinite(Date.parse(f.at)))&&validRound(s.active)&&(s.active===null||['spell','listen'].includes(s.active.mode));
  const store=new C.Store('garden',fresh,validate);
  const palettes=[['#ec8fab','#a75976','#f9d781'],['#f4c660','#b48b36','#784e2c'],['#a5a2e1','#6663ac','#f6da92'],['#ef9c70','#b46540','#f8d989'],['#84bdcc','#518f9e','#f9df89'],['#f2b8d2','#bb7d9b','#f9d894']];
  // Flower petal geometry adapted from David W Mpangala's MindBloom (MIT).
  // Attribution and full upstream license are in ../THIRD_PARTY_NOTICES.md.
  function flowerHead(v){const [petals,shadow,center]=palettes[v%palettes.length];const r=24,cx=56,cy=55,petalR=r*.62,orbitR=r*.72;let svg='';for(let i=0;i<8;i++){const angle=45*i-90,rad=angle*Math.PI/180,px=cx+Math.cos(rad)*orbitR,py=cy+Math.sin(rad)*orbitR;svg+=`<ellipse cx="${px.toFixed(1)}" cy="${py.toFixed(1)}" rx="${petalR}" ry="${petalR*.68}" fill="${petals}" transform="rotate(${angle+90},${px.toFixed(1)},${py.toFixed(1)})"/>`}return `${svg}<circle cx="56" cy="55" r="11" fill="${center}"/><circle cx="54" cy="52" r="4" fill="${shadow}" opacity=".3"/>`}
  function plantSVG(g,v=0){if(g===0)return '<svg width="160" height="72" viewBox="0 0 160 72"><ellipse cx="80" cy="62" rx="10" ry="6" fill="#d9ac6f" transform="rotate(-25 80 62)"/><path d="M74 60l12 4" stroke="#a17047" stroke-width="1.5"/></svg>';const height=g<30?60:g<60?108:g<100?157:178;const head=g<60?'':g<100?'<ellipse cx="56" cy="55" rx="13" ry="18" fill="#d792ac"/><path d="M47 66q9 -14 18 0" stroke="#58875b" fill="#58875b"/>':flowerHead(v);return `<svg width="156" height="${height+36}" viewBox="0 0 112 220"><path d="M56 212Q64 156 56 ${g>=60?69:150}" fill="none" stroke="#527c46" stroke-width="5" stroke-linecap="round"/><path d="M57 184Q15 176 27 149Q50 150 57 184" fill="#8bb578"/><path d="M57 165Q99 153 84 131Q64 137 57 165" fill="#72a768"/>${g>=30?'<path d="M56 131Q25 123 31 105Q49 109 56 131" fill="#91bd7c"/>':''}${head}</svg>`}
  let selected=[],locked=false,animating=false;
  function show(id){['home','study','result','history','collection'].forEach(x=>$(x).classList.toggle('hidden',x!==id));document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.tab===id)));window.scrollTo(0,0)}
  function renderHome(){const s=store.state;$('plant').innerHTML=plantSVG(s.growth,s.flowers.length%6);$('plant-label').textContent=`我的第 ${s.flowers.length+1} 颗种子`;$('stage-name').textContent=s.growth===0?'种子正在等你':s.growth<30?'一颗嫩芽，探出脑袋':s.growth<60?'小苗正在长出叶子':'花苞正在准备绽放';$('growth-label').textContent=`成长值 ${s.growth} / 100`;$('growth-fill').style.width=s.growth+'%';const next=s.growth===0?1:s.growth<30?30:s.growth<60?60:100;$('next-stage').textContent=`${next-s.growth} 点后${next===1?'萌芽':next===30?'长成小苗':next===60?'长出花苞':'开花'}`;$('bloom-count').textContent=`已开 ${s.flowers.length} 朵花`;$('water-count').textContent=`${s.water} 个水滴`;$('sun-count').textContent=`${s.suns} 个太阳`;$('water').disabled=!s.water||animating;$('sun').disabled=!s.suns||animating;const active=s.active&&s.active.phase!=='done';$('resume').classList.toggle('hidden',!active);if(active)$('resume-info').textContent=`${s.active.mode==='spell'?'拼字搭桥':'听音找花'} · 已完成 ${s.active.index+(s.active.phase==='answered'?1:0)} / 10 题`;$('start-spell').disabled=!!active;$('start-listen').disabled=!!active}
  function feed(resource){if(animating||!store.state[resource])return;let bloomed=false;if(!store.update(s=>{s[resource]--;s.growth+=resource==='water'?1:10;if(s.growth>=100){s.growth-=100;s.flowers.push({variety:s.flowers.length%6,at:new Date().toISOString()});bloomed=true}}))return;animating=true;C.sound(bloomed?'win':'drop');const element=$(resource==='water'?'pour':'shine');element.classList.remove('hidden');renderHome();if(bloomed){$('plant').innerHTML=plantSVG(100,store.state.flowers.at(-1).variety);$('stage-name').textContent='开花啦！这朵花已留在收藏里';C.toast('开花啦！新种子也准备好了。')}setTimeout(()=>{element.classList.add('hidden');animating=false;renderHome()},bloomed?2400:900)}
  function start(mode){if(store.state.active&&store.state.active.phase!=='done'){C.toast('先继续上次的学习，奖励已经替你保存。');return}const words=C.deck(store.state);if(mode==='spell'&&words.some(w=>!/^[a-z]+$/.test(w[0]))){C.toast('拼字关目前支持单个英文单词，请选听音关练习短语。');return}if(store.update(s=>{s.active={id:C.uid(),words,index:0,correct:0,missed:[],mode,phase:'ready',lastOK:false}})){show('study');renderQuestion()}}
  function choices(word){return C.shuffle([word,...C.distractors(word,store.state,3)])}
  function renderQuestion(){const a=store.state.active;if(!a)return;if(a.phase==='done'){renderResult();return}show('study');const w=a.words[a.index];selected=[];locked=a.phase==='answered';$('study-count').textContent=`第 ${a.index+1} / 10 题`;$('study-mode').textContent=a.mode==='spell'?'拼字搭桥':'听音找花';$('word-picture').textContent=a.mode==='spell'?w[2]:'🎧';$('study-prompt').textContent=a.mode==='spell'?`把“${w[1]}”拼到桥上`:'听一听，它是哪朵花？';$('spell-zone').classList.toggle('hidden',a.mode!=='spell');$('listen-choices').classList.toggle('hidden',a.mode!=='listen');$('feedback').textContent='';$('feedback').className='feedback';$('study-next').classList.add('hidden');$('walker').classList.remove('crossed');$('study-next').textContent=a.index===9?'查看这次收获 →':'下一题 →';if(a.mode==='spell'){const chars=C.shuffle(w[0].split('').map((ch,i)=>({ch,id:i})));$('letter-pool').replaceChildren();chars.forEach(({ch,id})=>{const b=document.createElement('button');b.className='letter';b.textContent=ch;b.dataset.id=id;b.draggable=true;b.onclick=()=>takeLetter(id,ch);b.ondragstart=e=>e.dataTransfer.setData('text/plain',String(id));$('letter-pool').append(b)});renderBridge()}else{$('listen-choices').replaceChildren();choices(w).forEach(option=>{const b=document.createElement('button');b.className='choice';b.textContent=option[1];b.dataset.answer=option[1];b.onclick=()=>answer(option[1]===w[1]);$('listen-choices').append(b)})}if(locked)showAnswer(a.lastOK)}
  function renderBridge(){const a=store.state.active;$('bridge').innerHTML=a.words[a.index][0].split('').map((_,i)=>`<span class="${selected[i]?'filled':''}">${selected[i]?E(selected[i].ch):'·'}</span>`).join('');document.querySelectorAll('.letter').forEach(b=>b.disabled=locked||selected.some(x=>x.id===Number(b.dataset.id)));$('submit-spell').disabled=locked||selected.length!==a.words[a.index][0].length;$('undo-letter').disabled=locked||!selected.length}
  function takeLetter(id,ch){if(locked||selected.some(x=>x.id===id))return;const a=store.state.active;if(selected.length>=a.words[a.index][0].length)return;selected.push({id,ch});renderBridge()}
  function showAnswer(ok){const a=store.state.active,w=a.words[a.index];locked=true;$('feedback').className='feedback '+(ok?'good':'bad');$('feedback').textContent=ok?'答对了！一滴水已经放进水壶 💧':`再记一次：${w[0]} = ${w[1]}`;$('study-next').classList.remove('hidden');if(a.mode==='spell'){if(ok)$('walker').classList.add('crossed');$('bridge').innerHTML=w[0].split('').map(ch=>`<span class="filled">${E(ch)}</span>`).join('');document.querySelectorAll('.letter').forEach(b=>b.disabled=true);$('submit-spell').disabled=true;$('undo-letter').disabled=true}else{document.querySelectorAll('#listen-choices .choice').forEach(b=>{b.disabled=true;if(b.dataset.answer===w[1])b.classList.add('correct')})}}
  function answer(ok){const a=store.state.active;if(!a||a.phase!=='ready')return;if(!store.update(s=>{s.active.phase='answered';s.active.lastOK=ok;if(ok){s.active.correct++;s.water++}else s.active.missed.push(s.active.words[s.active.index])}))return;C.sound(ok?'drop':'miss');showAnswer(ok)}
  function next(){const a=store.state.active;if(!a||a.phase!=='answered')return;C.stopSpeech();if(a.index===9){if(!store.update(s=>{const r=s.active;r.phase='done';if(!s.history.some(h=>h.id===r.id)){if(r.correct>=9)s.suns++;s.history.push({id:r.id,at:new Date().toISOString(),correct:r.correct,total:10,mode:r.mode==='spell'?'拼字搭桥':'听音找花'})}}))return;renderResult()}else if(store.update(s=>{s.active.index++;s.active.phase='ready'}))renderQuestion()}
  function renderResult(){const a=store.state.active;if(!a)return;show('result');$('result-title').textContent=a.correct>=9?'太阳也来为你加油了！':'每滴水，都能让花长大';$('result-score').textContent=`${a.correct*10}%`;$('result-reward').textContent=`收获 ${a.correct} 个水滴${a.correct>=9?' + 1 个太阳':''} · 可增加 ${a.correct+(a.correct>=9?10:0)} 点成长`;$('review').classList.toggle('hidden',!a.missed.length);$('review').innerHTML='<strong>下次再认识它们</strong>'+a.missed.map(w=>`<p>${E(w[0])} · ${E(w[1])}</p>`).join('')}
  function renderHistory(){$('stats').innerHTML=`<div><strong>${store.state.history.length}</strong><small>已保存的完整关卡</small></div><div><strong>${store.state.history.reduce((n,h)=>n+h.correct,0)}</strong><small>记录内答对单词</small></div><div><strong>${store.state.flowers.length}</strong><small>养出的花</small></div>`;$('history-list').innerHTML=C.historyRows(store.state)}
  function renderCollection(){const s=store.state;$('collection-list').innerHTML=s.flowers.length?s.flowers.map((f,i)=>`<div class="flower-card">${plantSVG(100,f.variety)}<strong>第 ${i+1} 朵小花</strong><small>${E(new Date(f.at).toLocaleDateString('zh-CN'))}</small></div>`).join(''):'<div class="empty-collection"><span>🌱</span><h3>第一朵花正在路上</h3><p class="muted">成长值到 100，它就会留在这里。</p></div>'}
  document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{C.stopSpeech();if(b.dataset.tab==='home')renderHome();if(b.dataset.tab==='history')renderHistory();if(b.dataset.tab==='collection')renderCollection();show(b.dataset.tab)});
  $('water').onclick=()=>feed('water');$('sun').onclick=()=>feed('suns');$('start-spell').onclick=()=>start('spell');$('start-listen').onclick=()=>start('listen');$('continue').onclick=renderQuestion;$('listen-word').onclick=()=>C.speak(store.state.active.words[store.state.active.index][0],ok=>{if(!ok)C.toast('设备暂时没有完成发音，可重新点“听英文”。')});$('undo-letter').onclick=()=>{if(!locked){selected.pop();renderBridge()}};$('submit-spell').onclick=()=>answer(selected.map(x=>x.ch).join('')===store.state.active.words[store.state.active.index][0]);$('bridge').ondragover=e=>e.preventDefault();$('bridge').ondrop=e=>{e.preventDefault();const id=Number(e.dataTransfer.getData('text/plain'));const b=document.querySelector(`.letter[data-id="${id}"]`);if(b)takeLetter(id,b.textContent)};$('study-next').onclick=next;$('study-exit').onclick=()=>{C.stopSpeech();renderHome();show('home')};$('return-garden').onclick=()=>{renderHome();show('home')};C.parentSetup(store,renderHome);C.install();renderHome();window.Garden={store,start,answer,next,feed,renderHome,validate};
})();
