(() => {
  'use strict';
  const C=GameCommon,{$,escape:E,int,validBase,validRound}=C;
  const fresh=()=>({version:1,app:'garden',settings:{pack:'pep5-photo-upper-all'},custom:[],water:0,suns:0,growth:0,selectedSeed:0,seedGrowth:[0,0,0,0,0,0],flowers:[],history:[],active:null});
  const validate=s=>validBase(s,'garden')&&C.validPlanting(s)&&int(s.water)&&int(s.suns)&&int(s.growth,99)&&Array.isArray(s.flowers)&&s.flowers.length<=10000&&s.flowers.every(f=>f&&int(f.variety,5)&&typeof f.at==='string'&&Number.isFinite(Date.parse(f.at)))&&validRound(s.active)&&(s.active===null||['spell','listen'].includes(s.active.mode));
  const store=new C.Store('garden',fresh,validate);
  if(!store.blocked&&!store.state.photoVocabularyRevision)store.update(s=>C.migratePhotoPack(s));
  const seeds=[{name:'玫瑰',english:'Rose',color:'#e785a1'},{name:'向日葵',english:'Sunflower',color:'#efbf45'},{name:'薰衣草',english:'Lavender',color:'#9a87d0'},{name:'郁金香',english:'Tulip',color:'#ee997a'},{name:'勿忘我',english:'Forget-me-not',color:'#7eb9db'},{name:'雏菊',english:'Daisy',color:'#f6faf3'}];
  function migratePlanting(){if(store.state.selectedSeed!==undefined)return;const initialize=s=>{s.selectedSeed=s.flowers.length%6;s.seedGrowth=[0,0,0,0,0,0];s.seedGrowth[s.selectedSeed]=s.growth};if(store.blocked||!store.update(initialize)){const display=C.copy(store.state);initialize(display);store.state=display;store.blocked=true}}
  migratePlanting();
  function flowerHead(v){
    const kind=v%6,color=seeds[kind].color;
    if(kind===0)return `<g fill="${color}" stroke="#b65c7d" stroke-width="1.4"><path d="M56 25C30 20 21 43 29 63C21 83 54 90 68 77C91 71 89 37 72 33C68 24 62 22 56 25Z"/><path d="M56 34C38 31 31 50 42 64C35 76 64 78 72 63C82 50 67 37 56 34Z" fill="#ed9eb3"/><path d="M49 44Q68 34 71 54Q69 72 50 68Q37 58 49 44Z" fill="#dd718f"/><path d="M56 47Q69 45 65 59Q53 68 49 55Q51 48 59 52" fill="none" stroke="#a95072" stroke-width="2.5"/></g>`;
    if(kind===3)return `<g stroke="#bd6749" stroke-width="1.5"><path d="M29 36Q44 32 56 51Q70 32 83 36L78 68Q56 96 34 68Z" fill="${color}"/><path d="M56 28Q35 50 47 77Q56 86 65 77Q77 50 56 28Z" fill="#f4b299"/></g>`;
    if(kind===2){let svg='<path d="M56 91V22M56 71L41 44M56 66L71 34" stroke="#70965e" stroke-width="2.5" fill="none"/>';for(const [x,y] of [[56,24],[52,33],[60,40],[53,47],[60,54],[52,61],[60,68],[44,42],[47,51],[69,32],[65,43]])svg+=`<ellipse cx="${x}" cy="${y}" rx="6" ry="5" fill="${y%2?'#b3a0e3':color}"/>`;return svg;}
    const count=kind===1?18:kind===4?5:12,orbit=kind===4?12:kind===1?22:19;let svg='';
    for(let i=0;i<count;i++){const angle=360*i/count-90,rad=angle*Math.PI/180,x=56+Math.cos(rad)*orbit,y=55+Math.sin(rad)*orbit;svg+=`<ellipse cx="${x.toFixed(2)}" cy="${y.toFixed(2)}" rx="${kind===4?12:kind===1?14:16}" ry="${kind===4?11:6}" fill="${color}" stroke="${kind===5?'#cbd8bc':kind===1?'#d8a237':'#639ec8'}" stroke-width=".8" transform="rotate(${angle},${x},${y})"/>`;}
    svg+=`<circle cx="56" cy="55" r="${kind===1?15:kind===4?6:10}" fill="${kind===1?'#765034':'#f3cc61'}"/>`;
    if(kind===1)for(const [x,y] of [[51,50],[61,50],[56,57],[49,60],[63,60]])svg+=`<circle cx="${x}" cy="${y}" r="1.8" fill="#ad8550"/>`;
    return svg;
  }
  function renderSeeds(){const s=store.state;$('seed-choices').innerHTML=seeds.map((seed,i)=>`<button type="button" class="seed-choice" data-seed="${i}" aria-pressed="${s.selectedSeed===i}" ${animating?'disabled':''}><span class="seed-preview">${plantSVG(100,i)}</span><strong>${seed.name}种子</strong><small>${seed.english}</small><span class="seed-progress">${s.seedGrowth[i]?`成长 ${s.seedGrowth[i]} / 100`:'等待种下'}</span></button>`).join('');document.querySelectorAll('[data-seed]').forEach(b=>b.onclick=()=>chooseSeed(Number(b.dataset.seed)));$('seed-note').textContent=`正在养${seeds[s.selectedSeed].name}。切换种子会保留各自成长，不消耗水滴或太阳。`;}
  function chooseSeed(id){if(animating||!int(id,5)||id===store.state.selectedSeed)return false;if(!store.update(s=>{s.seedGrowth[s.selectedSeed]=s.growth;s.selectedSeed=id;s.growth=s.seedGrowth[id]}))return false;renderHome();C.toast(`已选${seeds[id].name}种子，成长进度已保留。`);return true;}
  function plantSVG(g,v=0){if(g===0)return '<svg width="160" height="72" viewBox="0 0 160 72"><ellipse cx="80" cy="62" rx="10" ry="6" fill="#d9ac6f" transform="rotate(-25 80 62)"/><path d="M74 60l12 4" stroke="#a17047" stroke-width="1.5"/></svg>';const height=g<30?60:g<60?108:g<100?157:178;const head=g<60?'':g<100?`<ellipse cx="56" cy="55" rx="13" ry="18" fill="${seeds[v%6].color}"/><path d="M47 66q9 -14 18 0" stroke="#58875b" fill="#58875b"/>`:flowerHead(v);return `<svg width="156" height="${height+36}" viewBox="0 0 112 220"><path d="M56 212Q64 156 56 ${g>=60?69:150}" fill="none" stroke="#527c46" stroke-width="5" stroke-linecap="round"/><path d="M57 184Q15 176 27 149Q50 150 57 184" fill="#8bb578"/><path d="M57 165Q99 153 84 131Q64 137 57 165" fill="#72a768"/>${g>=30?'<path d="M56 131Q25 123 31 105Q49 109 56 131" fill="#91bd7c"/>':''}${head}</svg>`}
  let selected=[],locked=false,animating=false;
  function show(id){['home','study','result','history','collection'].forEach(x=>$(x).classList.toggle('hidden',x!==id));document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.tab===id)));window.scrollTo(0,0)}
  function renderHome(){migratePlanting();const old=store.state.active,allowed=new Set(C.words(store.state).map(w=>w[0]));if(old&&old.phase!=='done'&&old.words.some(w=>!allowed.has(w[0]))){if(store.update(s=>{s.active=null}))C.toast('旧练习超出当前范围，已按所选词库重新准备；奖励保留。')}const s=store.state;renderSeeds();$('plant').innerHTML=plantSVG(s.growth,s.selectedSeed);$('plant-label').textContent=`${seeds[s.selectedSeed].name} · 第 ${s.flowers.length+1} 朵花`;$('stage-name').textContent=s.growth===0?'种子正在等你':s.growth<30?'一颗嫩芽，探出脑袋':s.growth<60?'小苗正在长出叶子':'花苞正在准备绽放';$('growth-label').textContent=`成长值 ${s.growth} / 100`;$('growth-fill').style.width=s.growth+'%';const next=s.growth===0?1:s.growth<30?30:s.growth<60?60:100;$('next-stage').textContent=`${next-s.growth} 点后${next===1?'萌芽':next===30?'长成小苗':next===60?'长出花苞':'开花'}`;$('bloom-count').textContent=`已开 ${s.flowers.length} 朵花`;$('water-count').textContent=`${s.water} 个水滴`;$('sun-count').textContent=`${s.suns} 个太阳`;$('water').disabled=!s.water||animating;$('sun').disabled=!s.suns||animating;const active=s.active&&s.active.phase!=='done';$('resume').classList.toggle('hidden',!active);if(active)$('resume-info').textContent=`${s.active.mode==='spell'?'拼字搭桥':'听音找花'} · 已完成 ${s.active.index+(s.active.phase==='answered'?1:0)} / 10 题`;$('start-spell').disabled=!!active;$('start-listen').disabled=!!active}
  function feed(resource){if(!['water','suns'].includes(resource)||animating||!store.state[resource])return;let bloomed=false;if(!store.update(s=>{s[resource]--;s.growth+=resource==='water'?1:10;if(s.growth>=100){s.growth-=100;s.flowers.push({variety:s.selectedSeed,at:new Date().toISOString()});bloomed=true}s.seedGrowth[s.selectedSeed]=s.growth}))return;animating=true;C.sound(bloomed?'win':'drop');const element=$(resource==='water'?'pour':'shine');element.classList.remove('hidden');renderHome();if(bloomed){$('plant').innerHTML=plantSVG(100,store.state.flowers.at(-1).variety);$('stage-name').textContent='开花啦！这朵花已留在收藏里';C.toast(`${seeds[store.state.selectedSeed].name}开花啦！已放进收藏，可以继续养或换种子。`)}setTimeout(()=>{element.classList.add('hidden');animating=false;renderHome()},bloomed?2400:900)}
  function start(mode,restarting=false){if(!restarting&&store.state.active&&store.state.active.phase!=='done'){C.toast('先继续上次的学习，奖励已经替你保存。');return}const words=C.deck(store.state,mode);if(words.length!==10){C.toast('当前词库没有适合拼字的单词，请选听音关练习短语。');return}if(store.update(s=>{s.active={id:C.uid(),words,index:0,correct:0,missed:[],mode,phase:'ready',lastOK:false}})){show('study');renderQuestion()}}
  function restart(){const a=store.state.active;if(!a||a.phase==='done')return;C.stopSpeech();start(a.mode,true)}
  function choices(word){return C.shuffle([word,...C.distractors(word,store.state,3)])}
  function renderQuestion(){const a=store.state.active;if(!a)return;if(a.phase==='done'){renderResult();return}show('study');const w=a.words[a.index];selected=[];locked=a.phase==='answered';$('study-count').textContent=`第 ${a.index+1} / 10 题`;$('study-mode').textContent=a.mode==='spell'?'拼字搭桥':'听音找花';$('word-picture').textContent=a.mode==='spell'?w[2]:'🎧';$('study-prompt').textContent=a.mode==='spell'?`把“${w[1]}”拼到桥上`:'听一听，它是哪朵花？';$('spell-zone').classList.toggle('hidden',a.mode!=='spell');$('listen-choices').classList.toggle('hidden',a.mode!=='listen');$('feedback').textContent='';$('feedback').className='feedback';$('answer-review').hidden=true;$('answer-review').replaceChildren();$('study-next').classList.add('hidden');$('walker').classList.remove('crossed');$('study-next').textContent=a.index===9?'查看这次收获 →':'下一题 →';if(a.mode==='spell'){const chars=C.shuffle(w[0].split('').map((ch,i)=>({ch,id:i})));$('letter-pool').replaceChildren();chars.forEach(({ch,id})=>{const b=document.createElement('button');b.className='letter';b.textContent=ch;b.dataset.id=id;b.draggable=!locked;b.onclick=()=>takeLetter(id,ch);b.ondragstart=e=>e.dataTransfer.setData('text/plain',String(id));$('letter-pool').append(b)});renderBridge()}else{$('listen-choices').replaceChildren();(locked&&a.lastChoices?a.lastChoices.map(meaning=>[null,meaning]):choices(w)).forEach(option=>{const b=document.createElement('button');b.className='choice';b.textContent=option[1];b.dataset.answer=option[1];b.onclick=()=>answer(option[1]===w[1],option[1]);$('listen-choices').append(b)})}if(locked)showAnswer(a.lastOK)}
  function renderBridge(){const a=store.state.active;$('bridge').innerHTML=a.words[a.index][0].split('').map((_,i)=>`<span class="${selected[i]?'filled':''}">${selected[i]?E(selected[i].ch):'·'}</span>`).join('');document.querySelectorAll('.letter').forEach(b=>b.disabled=locked||selected.some(x=>x.id===Number(b.dataset.id)));$('submit-spell').disabled=locked||selected.length!==a.words[a.index][0].length;$('undo-letter').disabled=locked||!selected.length}
  function takeLetter(id,ch){if(locked||selected.some(x=>x.id===id))return;const a=store.state.active;if(selected.length>=a.words[a.index][0].length)return;selected.push({id,ch});renderBridge()}
  function showAnswer(ok){
    const a=store.state.active,w=a.words[a.index],submitted=a.lastAnswer===undefined?(ok?(a.mode==='spell'?w[0]:w[1]):null):a.lastAnswer;
    locked=true;$('feedback').className='feedback '+(ok?'good':'bad');$('feedback').textContent=ok?'答对了！一滴水已经放进水壶 💧':'这题答错了，看看下面的正确答案，再记一次。';
    $('study-next').classList.remove('hidden');
    $('answer-review').hidden=false;
    $('answer-review').innerHTML=`<p class="submitted-answer"><strong>你的答案：</strong>${submitted===null?'旧进度未记录当时的答案':E(submitted)} <span>${ok?'✓ 答对':'✗ 答错'}</span></p><p class="correct-answer"><strong>正确答案：</strong><span>${E(w[0])}</span> = ${E(w[1])}</p><p class="answer-hint">${ok?'读一遍记住它，再点“下一题”。':'上方保留你提交的答案。记住正确答案，再点“下一题”。'}</p>`;
    if(a.mode==='spell'){
      if(ok)$('walker').classList.add('crossed');
      $('bridge').innerHTML=submitted===null?'<small>旧进度没有记录提交内容</small>':submitted.split('').map((ch,i)=>`<span class="filled ${ch===w[0][i]?'':'wrong-letter'}">${E(ch)}</span>`).join('');
      document.querySelectorAll('.letter').forEach(b=>{b.disabled=true;b.draggable=false});$('submit-spell').disabled=true;$('undo-letter').disabled=true;
    }else{
      document.querySelectorAll('#listen-choices .choice').forEach(b=>{b.disabled=true;if(b.dataset.answer===w[1])b.classList.add('correct');if(b.dataset.answer===submitted){b.classList.add('submitted');if(!ok)b.classList.add('incorrect');b.setAttribute('aria-label',`${b.textContent}，你的选择，${ok?'答对':'答错'}`)}});
    }
  }
  function answer(ok,submitted){
    const a=store.state.active;if(!a||a.phase!=='ready')return;
    const value=submitted===undefined?(a.mode==='spell'?selected.map(x=>x.ch).join(''):undefined):submitted;
    const lastChoices=a.mode==='listen'?[...document.querySelectorAll('#listen-choices .choice')].map(b=>b.dataset.answer):null;
    if(!store.update(s=>{s.active.phase='answered';s.active.lastOK=ok;if(value!==undefined)s.active.lastAnswer=value;if(lastChoices)s.active.lastChoices=lastChoices;if(ok){s.active.correct++;s.water++}else s.active.missed.push(s.active.words[s.active.index])}))return;
    C.sound(ok?'drop':'miss');showAnswer(ok);
  }
  function next(){const a=store.state.active;if(!a||a.phase!=='answered')return;C.stopSpeech();if(a.index===9){if(!store.update(s=>{const r=s.active;r.phase='done';if(!s.history.some(h=>h.id===r.id)){if(r.correct>=9)s.suns++;s.history.push({id:r.id,at:new Date().toISOString(),correct:r.correct,total:10,mode:r.mode==='spell'?'拼字搭桥':'听音找花'})}}))return;renderResult()}else if(store.update(s=>{s.active.index++;s.active.phase='ready';delete s.active.lastAnswer;delete s.active.lastChoices}))renderQuestion()}
  function renderResult(){const a=store.state.active;if(!a)return;show('result');$('result-title').textContent=a.correct>=9?'太阳也来为你加油了！':'每滴水，都能让花长大';$('result-score').textContent=`${a.correct*10}%`;$('result-reward').textContent=`收获 ${a.correct} 个水滴${a.correct>=9?' + 1 个太阳':''} · 可增加 ${a.correct+(a.correct>=9?10:0)} 点成长`;$('review').classList.toggle('hidden',!a.missed.length);$('review').innerHTML='<strong>下次再认识它们</strong>'+a.missed.map(w=>`<p>${E(w[0])} · ${E(w[1])}</p>`).join('')}
  function renderHistory(){$('stats').innerHTML=`<div><strong>${store.state.history.length}</strong><small>已保存的完整关卡</small></div><div><strong>${store.state.history.reduce((n,h)=>n+h.correct,0)}</strong><small>记录内答对单词</small></div><div><strong>${store.state.flowers.length}</strong><small>养出的花</small></div>`;$('history-list').innerHTML=C.historyRows(store.state)}
  function renderCollection(){const s=store.state;$('collection-list').innerHTML=s.flowers.length?s.flowers.map((f,i)=>`<div class="flower-card">${plantSVG(100,f.variety)}<strong>${seeds[f.variety].name} · 第 ${i+1} 朵</strong><small>${E(new Date(f.at).toLocaleDateString('zh-CN'))}</small></div>`).join(''):'<div class="empty-collection"><span>🌱</span><h3>第一朵花正在路上</h3><p class="muted">成长值到 100，它就会留在这里。</p></div>'}
  document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{C.stopSpeech();if(b.dataset.tab==='home')renderHome();if(b.dataset.tab==='history')renderHistory();if(b.dataset.tab==='collection')renderCollection();show(b.dataset.tab)});
  $('water').onclick=()=>feed('water');$('sun').onclick=()=>feed('suns');$('start-spell').onclick=()=>start('spell');$('start-listen').onclick=()=>start('listen');$('continue').onclick=renderQuestion;$('restart').onclick=restart;$('listen-word').onclick=()=>C.speak(store.state.active.words[store.state.active.index][0],ok=>{if(!ok)C.toast('设备暂时没有完成发音，可重新点“听英文”。')});$('undo-letter').onclick=()=>{if(!locked){selected.pop();renderBridge()}};$('submit-spell').onclick=()=>answer(selected.map(x=>x.ch).join('')===store.state.active.words[store.state.active.index][0]);$('bridge').ondragover=e=>e.preventDefault();$('bridge').ondrop=e=>{e.preventDefault();const id=Number(e.dataTransfer.getData('text/plain'));const b=document.querySelector(`.letter[data-id="${id}"]`);if(b)takeLetter(id,b.textContent)};$('study-next').onclick=next;$('study-exit').onclick=()=>{C.stopSpeech();renderHome();show('home')};$('return-garden').onclick=()=>{renderHome();show('home')};C.parentSetup(store,renderHome);C.install();renderHome();window.Garden={store,start,restart,answer,next,feed,renderHome,validate,chooseSeed,seeds,plantSVG,renderCollection};
})();
