(() => {
  'use strict';
  const C=GameCommon,{$,escape:E,int,validBase,validWord}=C;
  const fresh=()=>({version:1,app:'navy',settings:{pack:'nature',mode:'word',difficulty:'easy'},custom:[],totalArrows:0,history:[],active:null});
  function validActive(a){return a===null||(a&&typeof a.id==='string'&&Array.isArray(a.words)&&a.words.length===10&&a.words.every(validWord)&&int(a.index,10)&&int(a.correct,10)&&int(a.arrows,10)&&Array.isArray(a.missed)&&a.missed.length<=10&&a.missed.every(validWord)&&Array.isArray(a.retryQueue)&&a.retryQueue.length<=10&&a.retryQueue.every(validWord)&&['ready','answered','victory','done'].includes(a.phase)&&typeof a.lastOK==='boolean'&&['word','meaning'].includes(a.mode)&&['easy','normal','fast'].includes(a.difficulty)&&(a.index<10||a.phase==='victory'||a.phase==='done'||a.retryQueue.length>0))}
  const validate=s=>validBase(s,'navy')&&['word','meaning'].includes(s.settings.mode)&&['easy','normal','fast'].includes(s.settings.difficulty)&&int(s.totalArrows)&&validActive(s.active);
  const store=new C.Store('navy',fresh,validate);let duration=22000,elapsed=0,lastFrame=0,raf=0,running=false,paused=false,listening=false,items=[],hasAudio=true;
  function boatSVG(arrows=0,capacity=4){let sticks='';for(let i=0;i<arrows;i++){const x=30+i*15;sticks+=`<path d="M${x} 40l-6-22m6 22l5-7m-5 7l-8-3" fill="none" stroke="#efe4bd" stroke-width="2"/>`}return `<svg viewBox="0 0 140 108" role="img" aria-label="草船，已收 ${arrows} 支箭"><path d="M13 76Q65 98 129 76L119 94Q63 114 22 95Z" fill="#7c4f36" stroke="#503b2a" stroke-width="2"/><path d="M11 76Q72 91 130 76" stroke="#c3a16c" stroke-width="4" fill="none"/><path d="M30 48Q68 20 109 48L109 78H30Z" fill="#b6a076" stroke="#625b43" stroke-width="2"/><path d="M34 48L42 72m3-29l8 31m3-35l8 35m4-37l8 39m4-37l9 34m3-29l8 31" stroke="#7b7654" opacity=".65" stroke-width="2"/><path d="M70 22V82" stroke="#bdae87" stroke-width="3"/><path d="M72 23L93 30 72 37Z" fill="#e0ccb0"/><circle cx="109" cy="64" r="5" fill="#d9c59e"/><path d="M105 70l7-2 4 11h-17Z" fill="#3f5354"/>${sticks}</svg>`}
  function fleetHTML(arrows){let remaining=arrows;return [4,3,3].map(cap=>{const n=Math.min(cap,remaining);remaining-=n;return `<div class="boat">${boatSVG(n,cap)}<div class="arrow-number">${n} / ${cap} 箭</div></div>`}).join('')}
  function show(id){['home','game','result','history'].forEach(x=>$(x).classList.toggle('hidden',x!==id));window.scrollTo(0,0)}
  function renderHome(){const s=store.state;$('hero-boats').innerHTML=fleetHTML(0);$('total-arrows').textContent=s.totalArrows;$('voyages').textContent=s.history.length;$('best').textContent=s.history.length?Math.max(...s.history.map(h=>h.correct))*10+'%':'—';['word','meaning'].forEach(mode=>$('mode-'+mode).setAttribute('aria-pressed',String(s.settings.mode===mode)));$('difficulty').value=s.settings.difficulty;const active=s.active&&s.active.phase!=='done';$('resume').classList.toggle('hidden',!active);$('start').disabled=!!active;if(active)$('resume-info').textContent=`已收 ${s.active.arrows} / 10 支箭 · ${s.active.phase==='victory'?'船队已满，来听诸葛亮道谢':s.active.index>=10?'还有单词等你再练一次':`已完成 ${s.active.index+(s.active.phase==='answered'?1:0)} / 10 个首答`}`}
  function currentWord(){const a=store.state.active;return a.index<10?a.words[a.index]:a.retryQueue[0]}
  function start(){if(store.state.active&&store.state.active.phase!=='done'){resume();return}const s=store.state;if(store.update(t=>{t.active={id:C.uid(),words:C.deck(s),index:0,correct:0,arrows:0,missed:[],retryQueue:[],mode:t.settings.mode,difficulty:t.settings.difficulty,phase:'ready',lastOK:false}})){show('game');prepare()}}
  function stop(){cancelAnimationFrame(raf);running=false;listening=false;C.stopSpeech()}
  function renderFleet(){$('fleet').innerHTML=fleetHTML(store.state.active.arrows);$('fleet-counter').textContent=`船队已收 ${store.state.active.arrows} / 10 支箭`}
  function prepare(){stop();const a=store.state.active;if(!a)return;show('game');if(a.phase==='done'){renderResult();return}renderFleet();$('thankyou').classList.add('hidden');$('next').classList.add('hidden');$('text-hint').classList.add('hidden');$('feedback').textContent='';$('feedback').className='feedback';$('rain-area').replaceChildren();$('question-count').textContent=a.index<10?`第 ${a.index+1} / 10 个单词`:'补练时间 · 帮船队收齐箭';$('mission-label').textContent=a.mode==='word'?'听英文 · 找英文':'听英文 · 找中文';$('time-fill').style.width='100%';$('time-label').textContent='听完再开始';$('pause').disabled=true;$('pause').textContent='暂停';$('replay').disabled=false;paused=false;elapsed=0;items=[];duration={easy:22000,normal:15000,fast:10000}[a.difficulty];$('launch-overlay').classList.remove('hidden');$('launch-title').textContent=a.index<10?'听清楚，再出箭':'这个词，再借一次';$('launch-note').textContent='单词下落时，点选你听到的那个';$('launch').textContent='听单词，开始这一波';$('launch').disabled=false;if(a.phase==='victory'){victory();return}if(a.phase==='answered'){showFeedback(a.lastOK);return}}
  function resume(){prepare()}
  function makeRain(){const a=store.state.active,w=currentWord(),field=a.mode==='word'?0:1;const pool=C.words(store.state);const candidates=C.shuffle([w,...C.shuffle(pool.filter(x=>x[field]!==w[field])).slice(0,5)]);$('rain-area').replaceChildren();items=candidates.map((word,i)=>{const b=document.createElement('button');b.className='rain-word';b.textContent=word[field];b.dataset.word=word[0];b.style.left=`${(i%3)*34}%`;b.onclick=()=>answer(word[field]===w[field]);$('rain-area').append(b);const startY=8+Math.floor(i/3)*82;const h=$('rain-area').clientHeight;return{b,startY,deadline:duration*(h-startY)/(h-8),target:word[field]===w[field]}});paint()}
  function begin(){const a=store.state.active;if(!a||a.phase!=='ready'||listening||running)return;if(!items.length)makeRain();$('launch').disabled=true;listening=true;$('launch-title').textContent='仔细听…';$('launch-note').textContent='播放结束后，单词才开始下落';C.speak(currentWord()[0],ok=>{listening=false;hasAudio=ok;if(!ok){$('text-hint').textContent=`设备暂时无法发音。看提示练习：${currentWord()[0]}`;$('text-hint').classList.remove('hidden')}$('launch-overlay').classList.add('hidden');paused=false;running=true;$('pause').disabled=false;$('pause').textContent='暂停';lastFrame=performance.now();raf=requestAnimationFrame(tick)})}
  function paint(){const h=$('rain-area').clientHeight;const target=items.find(x=>x.target);for(const item of items){const y=item.startY+elapsed/duration*(h-8);item.b.style.transform=`translateY(${y}px)`;item.b.disabled=!running||y>h;item.b.style.visibility=y>h+60?'hidden':'visible'}const left=target?Math.max(0,(target.deadline-elapsed)):duration;$('time-fill').style.width=Math.max(0,left/(target?.deadline||duration)*100)+'%';$('time-label').textContent=`还剩 ${Math.ceil(left/1000)} 秒`}
  function tick(now){if(!running)return;elapsed+=Math.min(100,now-lastFrame);lastFrame=now;paint();const target=items.find(x=>x.target);if(target&&elapsed>=target.deadline){answer(false);return}raf=requestAnimationFrame(tick)}
  function pause(){if(!running&&!paused)return;if(running){cancelAnimationFrame(raf);running=false;paused=true;items.forEach(x=>x.b.disabled=true);$('pause').textContent='继续';$('launch-overlay').classList.remove('hidden');$('launch-title').textContent='江上暂歇一会';$('launch-note').textContent='暂停时，单词和时间都停下来';$('launch').textContent='继续这一波';$('launch').disabled=false}else{paused=false;running=true;lastFrame=performance.now();$('pause').textContent='暂停';$('launch-overlay').classList.add('hidden');raf=requestAnimationFrame(tick)}}
  function answer(ok){const a=store.state.active;if(!a||a.phase!=='ready')return;const w=currentWord();if(!store.update(s=>{const r=s.active;r.phase='answered';r.lastOK=ok;if(ok){r.arrows++;s.totalArrows++;if(r.index<10)r.correct++}else if(r.index<10){r.missed.push(w);r.retryQueue.push(w)}if(r.arrows===10){r.phase='victory';if(!s.history.some(h=>h.id===r.id)){s.history.push({id:r.id,at:new Date().toISOString(),correct:r.correct,total:10,mode:r.mode==='word'?'听英文找英文':'听英文找中文'})}}}))return;stop();C.sound(ok?'drop':'miss');items.forEach(x=>x.b.disabled=true);renderFleet();if(ok){$('flight-arrow').classList.remove('hidden');setTimeout(()=>$('flight-arrow').classList.add('hidden'),650)}if(store.state.active.phase==='victory'){victory();C.speak('啊，谢谢大都督的赐箭！',()=>{},'zh-CN');return}showFeedback(ok)}
  function showFeedback(ok){const w=currentWord();$('launch-overlay').classList.add('hidden');$('pause').disabled=true;$('feedback').className='feedback '+(ok?'good':'bad');$('feedback').textContent=ok?'一箭入船！诸葛亮记下你的相助 🏹':`再听一次就会更熟：${w[0]} = ${w[1]}`;$('next').classList.remove('hidden');$('next').textContent=store.state.active.index>=9?'继续帮船队收齐箭 →':'下一波，继续借箭 →'}
  function next(){const a=store.state.active;if(!a||a.phase!=='answered')return;if(store.update(s=>{const r=s.active;if(r.index<10)r.index++;else{const first=r.retryQueue.shift();if(!r.lastOK)r.retryQueue.push(first)}r.phase='ready'}))prepare()}
  function victory(){stop();$('launch-overlay').classList.add('hidden');$('rain-area').replaceChildren();$('pause').disabled=true;$('replay').disabled=true;$('feedback').textContent='十支箭已收齐，船队可以归航了！';$('feedback').className='feedback good';$('thankyou').classList.remove('hidden');$('next').classList.add('hidden');$('time-label').textContent='借箭成功';$('time-fill').style.width='100%';renderFleet()}
  function renderResult(){const a=store.state.active;show('result');$('result-score').textContent=a.correct*10+'%';$('result-detail').textContent=`首答 ${a.correct} / 10 个单词正确 · 船队共收 10 支箭`;$('review').classList.toggle('hidden',!a.missed.length);$('review').innerHTML='<strong>这些词已经补练过，下次再认一次</strong>'+a.missed.map(w=>`<p>${E(w[0])} · ${E(w[1])}</p>`).join('')}
  function returnHome(){stop();if(store.state.active?.phase==='victory'&&!store.update(s=>{s.active.phase='done'}))return;renderHome();show('home')}
  $('mode-word').onclick=()=>{if(store.update(s=>{s.settings.mode='word'}))renderHome()};$('mode-meaning').onclick=()=>{if(store.update(s=>{s.settings.mode='meaning'}))renderHome()};$('difficulty').onchange=e=>store.update(s=>{s.settings.difficulty=e.target.value});$('start').onclick=start;$('continue').onclick=resume;$('launch').onclick=()=>paused?pause():begin();$('pause').onclick=pause;$('replay').onclick=()=>{if(store.state.active?.phase==='ready'){if(running){cancelAnimationFrame(raf);running=false}paused=false;begin()}else if(currentWord())C.speak(currentWord()[0])};$('next').onclick=next;$('save-exit').onclick=()=>{stop();renderHome();show('home')};$('finish-view').onclick=renderResult;$('return-home').onclick=returnHome;$('history-open').onclick=()=>{$('history-list').innerHTML=C.historyRows(store.state);show('history')};$('history-close').onclick=()=>{renderHome();show('home')};document.addEventListener('visibilitychange',()=>{if(document.hidden){if(running)pause();else if(listening){stop();$('launch').disabled=false;$('launch-title').textContent='回来后，再听一次';$('launch-note').textContent='当前单词和借箭进度已保留'}}});C.parentSetup(store,renderHome);C.install();renderHome();window.Navy={store,start,answer,next,prepare,validate,boatSVG,pause};
})();
